### ISSUE TITLE
Bladeshroom caps bounce off of rifters

### ISSUE THREAD

**Issue by cipherzerox** [Cryptic-Mushroom/The-Midnight#116]

**Comment by Corail31** [comment]
https://github.com/Cryptic-Mushroom/The-Midnight/blob/master/src/main/java/com/mushroom/midnight/common/entity/creature/EntityRifter.java#L222
intend feature ? :p

**Comment by Terenx** [comment]
the bladeshrooms bouncing off is because of some code I asked Gegy to put in to prevent players from bowspamming their way out of a rifters grasp before the stun ran out

**Comment by Terenx** [comment]
you could say it was an unintended consequence, but who cares, rifters are gonna become marauders in the midnight anyways xd

**Comment by Corail31** [comment]
fixed since [commit](https://github.com/Cryptic-Mushroom/The-Midnight/commit/cda1258c8ffa8b2a5e8e246647f74c4ddd6dfca7)
