### ISSUE TITLE
bladeshrooms should be placeable on walls and ceilings

### ISSUE THREAD

**Issue by five0five** [Cryptic-Mushroom/The-Midnight#130]
the stalk/spore would extend from the block its placed on, this would allow for bladeshrooms to be found on mushroom stems occasionally. It would also serve a purpose as a more compact mob farm or bladeshroom farm.

**Comment by ZombieEnderman5** [comment]
Very interesting. Might make for good mob traps (have a large shaft lined with bladeshrooms and knock mobs into it... By the time they hit bottom, they should be well and truly dead - variation on the long fall iron door trap)

**Comment by gegy1000** [comment]
Not nicely possible in 1.12. Block metadata is limited to 16 variants. 3 growth stages * 6 sides = 18 states.

**Comment by five0five** [comment]
ill leave this here then until 1.13
