### ISSUE TITLE
Rifter Pathfinding issue

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/The-Midnight#14]
If the route to the rift is too long the rifter might try to walk through solid blocks to try to get to it, this never works however, I tested this in a creative world and I made this long winding maze and at the end it was a stairway up and it dropped into a rift, I build a wall around the rift on the other ways, I have to make the wall 6 blocks thick to make em go through the very short tube to the rift

**Comment by gegy1000** [comment]
Had a similar issue a while back, but it was happening at much closer range. Linking the fix here for reference: https://github.com/Cryptic-Mushroom/Midnight/commit/c74125ea74abf6d6e96123693fab1fd27df0b7f8
