### ISSUE TITLE
Massive error spam on servers

### ISSUE THREAD

**Issue by cybercat5555** [Cryptic-Mushroom/The-Midnight#144]
The Midnight 0.2.0
Forge .2796

When added to a server (not a LAN), the mod creates massive spam of "An error has occurred with The Midnight" pop-ups, affected everyone on the server. I do not recall it making a crash log, but if needed I can try to make it happen again

**Comment by five0five** [comment]
I imagine this has stopped occurring in 0.3.1?

**Comment by Corail31** [comment]
@cybercat5555 you don't provide any info, as midnight got a new release, feel free to reopen this issue if you got this trouble again (and not the same as another issue already opened)
