### ISSUE TITLE
Rifter Grabbing Issue

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/The-Midnight#15]
Sometimes when a rifter jumps up or falls down a block to get to the rift while pulling something, they sometimes drop the mob, so if the rift is one y level above where the rifter and its intended grab target is, when it tries to jump up onto the ledge to level with the rift, on the jump it can drop the target

**Comment by gegy1000** [comment]
This one is very interesting. Whenever I try to reproduce it, it vanishes. :P 
I'm thinking it may be related to the captured bounding box intersecting with the rifter box.

**Comment by Terenx** [comment]
I think it’s them detaching, by a split second in between the jumps where the rifter is 1 total block above the capture target
