### ISSUE TITLE
Shadowroot chests merge with normal chests on a certain angle

### ISSUE THREAD

**Issue by SmellyModder** [Cryptic-Mushroom/The-Midnight#172]
When a shadowroot chest is placed adjacent to a normal chest in a certain direction it becomes one with the chest.

**Comment by ZombieEnderman5** [comment]
I wonder how you could possibly make the chest work then, wouldn't there be two tile entities for the two chest types? (Unless shadowroot converts to normal or normal converts to shadowroot.)
Either way it needs to be fixed eventually, I'm not great with coding so wouldn't be able to do anything

**Comment by SmellyModder** [comment]
Got mine to work in my mod so. ;) It's possible.
