### ISSUE TITLE
Bladeshroom caps should be craftable into spores

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/The-Midnight#178]
this not only helps people out by not forcing them to break the entire plant to make more but also makes sense in the fact that mushrooms usually store their spores in "gills" on the underside of the cap

**Comment by Terenx** [comment]
Watch me get told that you can get spores along with the cap when harvesting...

**Comment by five0five** [comment]
isn't this already the case?

**Comment by five0five** [comment]
i brought this up a while back and you can already do it lol

**Comment by Terenx** [comment]
I cant check i'm doing this on the school computer

**Comment by five0five** [comment]
I checked the code, its the case

**Comment by Terenx** [comment]
Isn't it great when you get things wrong...
