### ISSUE TITLE
Normal overworld mobs should not spawn in the midnight

### ISSUE THREAD

**Issue by Sunconure11** [Cryptic-Mushroom/The-Midnight#2]
I found some megalanias in the midnight. Reptile mod adds them, and yet they weren't sucked up by a portal to the realm so they shouldn't be there.

**Comment by Sunconure11** [comment]
I'm seeing some overworld gen from other mods that shouldn't be in this plane, either, such as berry bushes from Plants 2.

**Comment by gegy1000** [comment]
This is odd because it seems like these are issues with the other mods, though these issues aren't present with other dimension mods. Will have to look into it.

**Comment by Sunconure11** [comment]
So far, I've seen Reptile Mod mobs, Mob Mash mobs, and Eyes in the Darkness mobs.

**Comment by gegy1000** [comment]
This is possibly due to the Midnight biomes being added to the BiomeDictionary automatically. It seems like a hacky solution to exclude it completely from the BiomeDictionary, though.
