### ISSUE TITLE
Normal Tall midnight grass and Lumen Buds cannot be bonemealed to be double tall

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/The-Midnight#20]

**Comment by gegy1000** [comment]
How should this be applied to mushrooms? They also have double tall variants, but growing the small variants grows into the huge structure. Possibly the double variants would grow into the large mushrooms instead?

**Comment by cipherzerox** [comment]
That works

**Comment by Terenx** [comment]
maybe bonemealing a small one can still spawn the giant structure, but it has a decreased chance and on failure it just becomes double tall, which then has the normal chance, or maybe the small ones can have a special fertilizer to make them double tall, and you could bonemeal the small one to make the structure but the double tall would act like saplings, growing by themselves eventually but can still be bonemealed.

**Comment by Terenx** [comment]
but wait, how would bone meal work in the midnight, there might need to be a bonemeal variant, like "crushed pearls" which would be basically ground dark pearls.
