### ISSUE TITLE
Quark ladder incompat

### ISSUE THREAD

**Issue by five0five** [Cryptic-Mushroom/The-Midnight#203]
When quark is installed, placing a ladder on a ladder places a ladder underneath it
This doesn't apply to midnight's ladders

**Comment by Andromander** [comment]
According to the source from [Quark](https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/tweaks/feature/DeployLaddersDown.java), only regular Ladders and Quark's Iron Ladders can work with this feature.

**Comment by gegy1000** [comment]
Following from what @Andromander said, this wouldn't really be something we can do from our side, unfortunately.
