### ISSUE TITLE
Mob Spawn 

### ISSUE THREAD

**Issue by LokyLive** [Cryptic-Mushroom/The-Midnight#209]
Hello i've tryed the midnight dimension and i want to add in my modpack but for some reason i can't make spawn "Rogue Android" from Matter overdrive in the Midnight dimension. Is this a bug ?

**Comment by five0five** [comment]
https://imgur.com/vKFOHgd

I have no context on this mod, but I'm using the spawn egg here and it appears to be working. Check you aren't in peaceful difficulty

**Comment by SmellyModder** [comment]
I don't know anything about that mod, but are you saying that you're trying to make the dimension itself start spawning something? If so, I think Midnight has a custom way of spawning mobs for the dimension, which may explain it. Though commands and spawn eggs shouldn't be affected by the custom spawn mechanics.

**Comment by LokyLive** [comment]
I just want to add to the normal spawn of Midnight the Rogue Android  and i'm using Matter overdrive cfg where you can specify dimension whitelist for spawn

**Comment by SmellyModder** [comment]
Yeah then it might have to due with the custom spawn stuff for Midnight.

**Comment by Corail31** [comment]
the RogueAndroid requires the allowed biome to be set in the cfg too i suppose (as the code refers to it)
so midnight:vigilant_forest and so on :)

**Comment by LokyLive** [comment]
I've tryed many change without any success (weight=100 the dimension crash) 
https://paste.dimdev.org/zegicafoni.bash

**Comment by MokahTGS** [comment]
I've tried this mod and have Lycanites mobs spawning without doing anything, but that mod does tend to over right all other mods spawning rules.

I'd like to see this mod with more robust spawning configs that allow for other mods mobs as well.

**Comment by five0five** [comment]
I believe lycanites has a spawning blacklist, if you want to stop them from spawning in the dimension

**Comment by knoxhack** [comment]
I'm having the same problem, I tried to spawn some mobs in there but they won't spawn, when I add them to another dimension they spawn just right

**Comment by knoxhack** [comment]
I tried using Spawn Table Tweaker:
https://minecraft.curseforge.com/projects/spawntabletweaker

**Comment by Corail31** [comment]
@knoxhack In the last beta, the lists of spawn of creatures have been replaced by a weighted list (but actually, it doesn't use anymore the biome lists, so mods adding spawns by this way can't)

**Comment by knoxhack** [comment]
Yeah, that's why this could not work :( 
`//mods.spawntabletweaker.addSpawn("thaumcraft:eldritchguardian", 50, 2, 5, "MONSTER",["midnight:vigilant_forest","midnight:black_ridge","midnight:deceitful_bog","midnight:fungi_forest","midnight:obscured_peaks","midnight:warped_fields","midnight:crystal_spires","midnight:night_plains","midnight:obscured_plateau","midnight:phantasmal_valley","midnight:runebush_grove","midnight:hilly_vigilant_forest","midnight:hilly_fungi_forest"]);`

**Comment by gegy1000** [comment]
This should be fixed in 1.14
