### ISSUE TITLE
Shovel mining speed on midnight dirt/grass is always the same

### ISSUE THREAD

**Issue by Kiyaku** [Cryptic-Mushroom/The-Midnight#210]
It seems like it doesn't matter what harvest level your shovel has, midnight dirt and grass always gets mined at the same speed (same speed as if you had no tool and just used your hands). 

Using The Midnight version 0.3.1

**Comment by Corail31** [comment]
Thanks for the issue, Kiyaku, and don't hesitate to post new issues like this one that help to improve the mod :)

**Comment by Kiyaku** [comment]
Anytime! Been enjoying it a lot, and currently making a pack where i'd use this dimension only (no overworld). So chances are i might found more stuff :) (also in discord, username there is SeriousCreeper),
