### ISSUE TITLE
You can "override" 1-tall plants (like lumen bed or dewshroom) with blocks

### ISSUE THREAD

**Issue by Kiyaku** [Cryptic-Mushroom/The-Midnight#211]
Heya,

i noticed that trying to place a block "against" a 1-tall plant actually places the block in the same space, similar to how you can place blocks on top of 1-tall grass. 

Comparing this to vanilla plants (like poppies), they probably shouldn't override them.

2-tall versions of said plants work fine and do not get overridden.

**Comment by Corail31** [comment]
I think it was only on double plant, but if you see others plants, just reopen the issue :)
