### ISSUE TITLE
Portal Crashes When Entering From BoP Wasteland

### ISSUE THREAD

**Issue by BTRBT** [Cryptic-Mushroom/The-Midnight#212]
Client crashes when trying to enter the rift / portal from a Biomes O Plenty Wasteland.

Crashlog linked here: https://pastebin.com/raw/2mV32FhV

**Comment by Corail31** [comment]
Hi BTRBT,
actually, i made tests and i never succeed to reproduce this crash with only BOP & Midnight (but same version as you) so, can you make the tests with only Midnight and BOP ?

**Comment by Corail31** [comment]
Thanks for your help, BonesTheRabbit ;)
