### ISSUE TITLE
[discussion] Small Suggestions for this up and coming awesome mod!

### ISSUE THREAD

**Issue by SirAron111** [Cryptic-Mushroom/The-Midnight#213]
First of all I love the concept of this mod once this in release state and I don’t get stuck underground when entering the rift I want to add it to my Modpack.
On that note I have a few suggestions I would like to make for you to think about.
1.	An item to close a rift with a configurable amount of uses (I would make it a onetime use thing for my pack)

2.	An item to exit the dimension from everywhere so you don’t always have to search for a portal (I once spend 1 hour looking for one to get back to the over world) (item should be crafted with materials you can farm in the new dimension).

3.	More mobs to spawn from the Rifts or at least some that spawn in the dimension. Like fling eyeballs or shadow creatures etc. to fit the theme.

4.	Second type of Rifts that spawn flat on the ground XD rarer than the upright ones but would make for a fun surprise when stepping into one.

5.	Some vertically shafts in the over ground of the new dimension that lead straight down to the cave layer of it. But really straight so like a vertically drop XD with a puddle/pool of water or so at the bottom or even better a mushroom with a bouncy top.

6.	A machine/Block/Rift Stabilizer: That prevents Rifts from spawning in a set are (powered with something like RF or a farmable ingredient from the new dimension like a growable crystals or something as fuel) (making the recipe a bit harder and endgame or letting it blank for people to make custom recipes for it with minetwearker etc.)

7.	(Will add some more if I have more ideas)

If you like one of these ideas tell me XD would be happy if even one makes it.
Thx for reading this hope the mod will become even more awesome and bug free.

GZ
SirAron

**Comment by five0five** [comment]
Some of these sound pretty cool, just in case you were unaware, lightsources already close rifts.

**Comment by SirAron111** [comment]
ye but just placing a torch near a rift is to easy (well for my Modpack it would be that is) having the light source closing it as a config option would be nice default it to “true” and you won’t change the basic feature but would enable Modpack to have the closing of these rifts be just at daytime or with a harder to craft (designated) item than a torch.

I myself don’t know much about Modding but I know how to mess with configs to get things working the way I want them to as a Modpack maker and for me having options in the config is the best solution to change things around. This is my current pack ( https://minecraft.curseforge.com/projects/dimension-zero )
I am currently using DimDoors to generate rift like things but they are ugly and I can’t (because it corrupts the save files) enable the rest of that mod. And once removed the never come back making them literally insignificant for the story. 
So when I saw this Awesome Mod I was all over it following and testing it since it got put on curse. As it would be the perfect replacement/improvement I needed.

**Comment by SirAron111** [comment]
Another feature that would be nice would be to have the player be teleported back to the place he entered the rift dimension as  you have to run quiet far in the dimension to find a Rift to get you back out randomly spawning in a strange location back in the over world is kind of hard to deal with.

**Comment by CursedFlames** [comment]
> Another feature that would be nice would be to have the player be teleported back to the place he entered the rift dimension

I kinda disagree with this, Midnight is quite nice for travelling without having to deal with overworld terrain and monsters. Config option, maybe?

**Comment by SirAron111** [comment]
Yes I agree this should be a config option since for vanilla/light modded traveling effect is nice but for heavy modded packs if you get separated from your base with no teleportation means you are pretty much out XD.

But most of all there should be an item that can be used to teleport you back/summon a rift to get back created with simple items from the new dimension.

If only the first 2 ideas I had make it into the mod be it as items or as config options,

•	An item to close a rift with a configurable amount of uses (I would make it a onetime use thing for my pack) (light is to easy config option to turn spawn prevention from light and instead use a set item would be nice)
•	An item to exit the dimension from everywhere so you don’t always have to search for a portal (I once spend 1 hour looking for one to get back to the over world) (item should be crafted with materials you can farm in the new dimension).

I could finally add it to my pack as a core feature of the hostile environment I already have invasions and other deadly things and was thinking of replacing the Rifts (only ambient and bad looking from dimdoors) with this cool mod but atm it’s just not configurable enough and a bit to buggy so I am waiting excitedly for the next update that promised to fix a lot of crashes and spawn in wall issues.

**Comment by cipherzerox** [comment]
All of these ideas are great ideas in and of themselves. For the rift-related things, most of it is already planned in some form iirc. I might be getting confused. 

Anyway, I'm all for enabling a different item to be used for closing rifts as well as a lightsource. Actually, another lightsource from Midnight would be feasible, I think. We definitely have another rift-related monster planned, but others would be great as well. I thought we had a rift stabilizer of some sort planned, but not a machine iirc. We definitely have an item to open new rifts planned.

With that said, I love that structure idea. I doubt it will get implemented exactly as you described, but we could do something like that. ^^
