### ISSUE TITLE
Crash when trying to load Midnight on a server

### ISSUE THREAD

**Issue by cybercat5555** [Cryptic-Mushroom/The-Midnight#216]
crash: https://gist.github.com/Ri5ux/f688c04e01569db0ecbb2f6aae430cb5
Midnight 0.3.0
Upon trying to load The Midnight on a server, the above crash occurred.

**Comment by five0five** [comment]
please use 0.3.1

**Comment by five0five** [comment]
Closing, refers to an outdated version known not to work on servers.
