### ISSUE TITLE
The animation doesn't show when using Immersive Engineering heaters.

### ISSUE THREAD

**Issue by ProsperCraft** [Cryptic-Mushroom/The-Midnight#217]
![2019-03-17_21 24 36](https://user-images.githubusercontent.com/4427684/54505753-d7261100-48fe-11e9-8763-a4911785a9fb.png)

As you can see the vanilla furnace plays the animation showing it is cooking, but the midnight furnace is not, they both have items and are cooking.

**Comment by Corail31** [comment]
Thanks for you report, Goshen :)
