### ISSUE TITLE
Client crashes CEE in the overworld caught by vanillafix.

### ISSUE THREAD

**Issue by ProsperCraft** [Cryptic-Mushroom/The-Midnight#218]
https://gist.github.com/ProsperCraft/bcf868b7fe6634e634605e7086533360

**Comment by Corail31** [comment]
fixed in 0.3.3 [commit](https://github.com/Cryptic-Mushroom/The-Midnight/commit/a1aed0962c3495a5e44d389d3b6ab9d34c3183b2)
