### ISSUE TITLE
The Sky doesn't play nice with Sildur's vibrant shaders (High)

### ISSUE THREAD

**Issue by Buttcrackofthunder** [Cryptic-Mushroom/The-Midnight#219]
hey, that rhymed

Going to the dimension with those on makes the sky freeze in exactly the way it looked when you left the overworld. the shader-sky freezes locked to your camera and moves with it.

the rift is also overbright, but I think it adds a nice ambiance.

**Comment by five0five** [comment]
1.14 has a new skybox, reopen I guess if this still occurs when 1.14 is release, however this is more on their side afaik
