### ISSUE TITLE
Single player crash when going through The Midnight portal -WorldGenMidnightCaves.getRadiusScale

### ISSUE THREAD

**Issue by ProsperCraft** [Cryptic-Mushroom/The-Midnight#221]
https://gist.github.com/ProsperCraft/afc87c4ce85ac619febb49a126c6a866

Modpack - [https://minecraft.curseforge.com/projects/drtardis-2-new-adventures](https://minecraft.curseforge.com/projects/drtardis-2-new-adventures)

**Comment by gegy1000** [comment]
This is related to #212 -- it will be resolved in the next update.
