### ISSUE TITLE
BYG Biomes generating in the midnight

### ISSUE THREAD

**Issue by thanasishadow** [Cryptic-Mushroom/The-Midnight#222]
Some biomes from [THIS](https://minecraft.curseforge.com/projects/oh-the-biomes-youll-go) mod are generating in the Midnight dimension. Blocks are being replaced by appropriate ones (nightstone for example). The problem is that plants also generate along these biomes and they aren't being replaced nor removed.
[![javaw-2019-03-31-20-27-24.png](https://i.postimg.cc/dVjYqWt7/javaw-2019-03-31-20-27-24.png)](https://postimg.cc/ZWngHxNZ)

**Comment by gegy1000** [comment]
Hm, I haven't looked into it at all but I believe this is an issue with their mod. It's likely hooking into the genlayer event, but not checking dimension

**Comment by Corail31** [comment]
@thanasishadow on the same time, you're using a mod done with MCreator, so it would be hard to be compatible with a mod done by auto generated code...

**Comment by five0five** [comment]
closing because the bug is down to an mcreator mod, if something like this occurs with another (non mcreator) mod, open a new issue
