### ISSUE TITLE
Crash upon entering through the portal, suspected issue with Just a Few Fish

### ISSUE THREAD

**Issue by DWX12** [Cryptic-Mushroom/The-Midnight#223]
Got a crash report upon entering the dimension. VanillaFix suspects that it has something to do with both Midnight and Just a Few fish. Don't know much more than that. 

https://paste.dimdev.org/anugedobin.mccrash

I have been having problems with Minecraft crashing when entering the dimension lately. I'll be sure to post any other crash reports that list other odd mod interactions.

**Comment by Corail31** [comment]
https://github.com/Cryptic-Mushroom/The-Midnight/issues/221

**Comment by DWX12** [comment]
Alright, looks like you guys have it sorted it out then.

Many thanks.

**Comment by Corail31** [comment]
fixed in 0.3.3
