### ISSUE TITLE
Novas suffocating to death

### ISSUE THREAD

**Issue by ZombieEnderman5** [Cryptic-Mushroom/The-Midnight#225]
Novas will suffocate to death in Dark Water in the Midnight. That's all there is to say. Not sure why this happens, but I've observed you can also punch them into the sides of hills and they'll suffocate then as well (does happen with blocks you can sink into - they'll suffocate in both Deceitful Mud and vanilla Soul Sand). In case of confusion, second image is inside of Dark Water. Midnight version: 0.3.1
![Suffocating in Deceitful Mud](https://user-images.githubusercontent.com/37218872/56065154-0b47f280-5d42-11e9-89fc-a3f74af7f7f1.png)
![Suffocating in Dark Water](https://user-images.githubusercontent.com/37218872/56065155-0b47f280-5d42-11e9-9af2-315d47866c68.png)
![Suffocating in plain hill](https://user-images.githubusercontent.com/37218872/56065156-0b47f280-5d42-11e9-87b3-7de189d1e97f.png)
![Suffocating in artificially built Soul Sand mound](https://user-images.githubusercontent.com/37218872/56065157-0b47f280-5d42-11e9-974f-1b7efefe25e5.png)

**Comment by ZombieEnderman5** [comment]
**Possibly important note:** Midnight is not the only mod in the configuration/profile I was using when this issue occurred. Other mods in configuration/profile: ActualMusic 5 (mostly client mod), Embassy (required to run AM5), Gaia Dimension, Nifty, ReAuth (used for re-logging in while Minecraft is open, mainly for the case of being unable to join a server due to invalid session), and CTM.

**Comment by five0five** [comment]
Doesn't happen on 1.14 by my testing, if it does, please reopen the issue
