### ISSUE TITLE
Unstable Seeds don't make a sound on placement

### ISSUE THREAD

**Issue by five0five** [Cryptic-Mushroom/The-Midnight#226]
placing on midnight grass

**Comment by Jonathing** [comment]
I don't know if they're supposed to. When you place vanilla seeds down in the overworld, they don't make sounds either. That's completely intentional.

**Comment by five0five** [comment]
that was changed in 1.14 + even in 1.12 the farmland makes a sound when you place them iirc

**Comment by Jonathing** [comment]
Idk man because I was in 1.12 when I tested placing seeds on farmland.

Also, we haven't made the mod for 1.14 so the game doesn't know what sound
exists for placing seeds down, yet.

**Comment by five0five** [comment]
I think the sound is an indicator the block's actually been placed, also unstable seeds don't have a placement animation

**Comment by five0five** [comment]
fixed on 1.14
