### ISSUE TITLE
Rifters Dragging Huge Mobs

### ISSUE THREAD

**Issue by five0five** [Cryptic-Mushroom/The-Midnight#229]
I've seen several reports of this on discord but it's still not on GitHub, so I thought I'd put it here myself. Rifters can drag huge mobs like ice and fire dragons, maybe they should have a check for hitbox size and/or mob health. Additionally, @SirAron111 who posted the dragon issue on discord, suggested a potential blacklist for mobs rifters can drag.

**Comment by SirAron111** [comment]
Generally a Blacklist for entities to even get sucked trough the rifts would be nice there are some things that count as entities and thus get through the first even if they totally shouldn’t like Falling Dynamic Trees.

Also checking for mob health wouldn’t be that good as in cases like my modpack which have the scaling health mod so most mobs will end up with nearly 1k or more hp at some point.
