### ISSUE TITLE
[feature] Suggestion: Little Tamable Shadow creatures Idea (feedback appreciated)

### ISSUE THREAD

**Issue by SirAron111** [Cryptic-Mushroom/The-Midnight#238]
I made this Suggestion once in the flow of a conversation on the Discord but and since some people liked it I will now make a proper one.

I had this Idea on what not Hostile mob would be fitting for the Midnight and thought that a Little rather cute but shadow like creature that has an AI similar to the Minecraft bunny (without the Jumping) where it mostly runs away but can still be tamed if given (X food item from the Midnight Dimension) would be the best bet.

Here are some Pictures of what I had in mind (These aren’t my pictures I just found them on the Internet and I know it’s mostly impossible to make something this cut in blocky Minecraft XD but it’s just about the Idea)

![Shadow Critters](https://user-images.githubusercontent.com/39855956/59637793-f54a1a00-9156-11e9-8245-b9b3bd429478.jpg)

![Small Red](https://user-images.githubusercontent.com/39855956/59637834-0d219e00-9157-11e9-81ac-9338748cd82e.png)

Their Eyes or features could be color changing like the antlers of the Nightstags.
Obviously the models would be Blockyfied Minecrafty Style.

And who wouldn’t want something as cute as this as a pet when wandering through the dark realms of the Midnight as a companion.

And as an extra there is even the possibility of having bigger ones spawn as hostiles or raising the small ones into big tame ones that look more like this XD. Like this

![Big Red](https://user-images.githubusercontent.com/39855956/59637856-19a5f680-9157-11e9-979a-ea8500e08f49.png)

**Comment by cipherzerox** [comment]
This idea is amazing. I definitely like the passive shadow creatures that can be tamed, but I'm not sure about hostile versions. :)

**Comment by SirAron111** [comment]
The hostile is just an extra idea the main idea is defenetly about the critters.

**Comment by cipherzerox** [comment]
Yeah the main idea is awesome. I'd love to implement it.

**Comment by AuraGlitch** [comment]
I would love to see this, honestly I was wanting a tamable creature, have you thought of contribute on this mod? I think you have good touches for it!

**Comment by SirAron111** [comment]
I can only contribute with ideas. I can’t draw at all these pictures are from the internet. And I also cant code more than changing around some config I am just a Modpack maker… meaning I take stuff others made and pretend I am am the biggest boss by smashing them all together Xd. (Well there is a little bit more to it than smashing it all together but well that’s of no concern here.)

**Comment by Jonathing** [comment]
This is an incredibly intriguing suggestion. I'll keep note of it.

**Comment by SirAron111** [comment]
Was a realy fun game (A hat in time) and a realy anoying one when you had to beat all of Snatchers special quests after the amin story XD still fun. sad that no support for 1.12.2 is in the mod anymore.

**Comment by Jonathing** [comment]
Yeah, well the jump in methods from 1.12 and 1.14 is so great that it's not worth it. I may work in a final release for 1.12.2 in which I fix some critical bugs, but I would be the only one to work on that. Plus, no promises.

**Comment by Jonathing** [comment]
@SirAron111 We do plan on adding these shadow creatures into The Midnight 0.6.0. If you'd like to elaborate on anything you suggested here, feel free, or you can do so on our Discord server! I'll close this issue once 0.6.0 has been released.
