### ISSUE TITLE
Spore Bombs crash server after detonation

### ISSUE THREAD

**Issue by GXyon** [Cryptic-Mushroom/The-Midnight#239]
The spore bombs cause a fatal crash on servers, rendering the world inaccessible unless directly erasing the affected chunk through the world's region files. However, the bombs work perfectly on single-player worlds.

Crash Log: https://pastebin.com/g0edHG4n

**Comment by Corail31** [comment]
Thank you for reporting this issue, GXyon. It's now fixed in dev.
