### ISSUE TITLE
Error spam on server

### ISSUE THREAD

**Issue by MartijnMilius** [Cryptic-Mushroom/The-Midnight#243]
I keep getting the message "An error has occurred with The Midnight" pop-up. Using a multiplayer server, not lan. 

Error log:
https://paste.dimdev.org/ugocajajam.mccrash

Any idea?

**Comment by MartijnMilius** [comment]
Using the latest forge, latest midnight version, if that matters. Errors only occur at night, my guess is when a portal spawns?

**Comment by five0five** [comment]
if this occurs on 1.14, reopen
