### ISSUE TITLE
Fire mechanics in the Midnight

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/The-Midnight#25]
The way I see it, a lot more than you think should be consumed by fire, the midnight is a dimension of darkness, and it reminds me of the underneath in Stranger Things, I should think that almost any vegetation in this should be destroyed by fire, but nothing is consumed by fire, heck, the leaves cant even have fire on them in the first place.

Additionally, Miasma's interaction with fire should be thought about.

**Comment by gegy1000** [comment]
Ah yes. This is definitely something we should think about.
