### ISSUE TITLE
[Localization] Russian translation for The Midnight 0.3.5

### ISSUE THREAD

**Issue by mrJyggalag** [Cryptic-Mushroom/The-Midnight#252]
Just a simple translation into Russian language. Nothing remarkable, here is the [link](https://drive.google.com/file/d/1Ti003MFwmCCt6DYIxsxsk0tzsB5KnGW9/view?usp=sharing) to Google drive

**Comment by mrJyggalag** [comment]
UPD: fixed some items/entities translation. The new version of the translation is available at the link from the main comment

**Comment by Corail31** [comment]
@mrJyggalag : be sure to always make your change from the new version of the file (as i compare the files and fixed an incorrect key, "misama") : [actual version for 1.12.2](https://github.com/Cryptic-Mushroom/The-Midnight/blob/1.14.3/src/main/resources/assets/midnight/lang/ru_ru.json)

**Comment by gegy1000** [comment]
@Corail31 can this be closed following your commit? :)

**Comment by Corail31** [comment]
sure
