### ISSUE TITLE
Bug with Thaumcraft generation

### ISSUE THREAD

**Issue by mrJyggalag** [Cryptic-Mushroom/The-Midnight#255]
In Midnight i found...this:
![image](https://user-images.githubusercontent.com/25662632/61596571-067ebe80-ac0e-11e9-8953-51992d352714.png)
This is Midnight bug or Thaumcraft bug?

Midnight version  - 0.3.5
Thaumcraft version - 6.1.BETA26 (Oct 18, 2018)

**Comment by gegy1000** [comment]
Sorry for very late reply.. I'm not sure -- I'd be inclined to say it's a Thaumcraft bug, but maybe I'm wrong

**Comment by five0five** [comment]
I don't even know if that's a bug, it probably spawns based on biome category (in this case, forest) and doesn't check for dimension, there may be an option in their config

**Comment by five0five** [comment]
if this occurs on 1.14 (not sure how it would lol), reopen
