### ISSUE TITLE
Crash Mid Game

### ISSUE THREAD

**Issue by TheQKnight** [Cryptic-Mushroom/The-Midnight#256]
Just mid game, my screen seems to be flooded with error notifications from vanillafix that midnight had encountered a problem. Here is my log: https://pastebin.com/9JxkFssv . It eventually crashed, but I'm not sure if that was due to NEI or Midnight.

I posted this crash on the NEI github too. If anyone could help me figure out whats going on. it would be greatly appreciated.

**Comment by Corail31** [comment]
Hi TheQKnight, this issue similar to #243, so i prefer to close it to avoid dupe.
