### ISSUE TITLE
Minecraft Crashes During Initialization 

### ISSUE THREAD

**Issue by ResidentCoder2** [Cryptic-Mushroom/The-Midnight#259]
I fixed this by removing the midnight mod from my mod folder, but I'd really like to keep it. Help me out? Provided a crash log and video of the game initialization before crashing below:

**Youtube Crash Video:**

https://www.youtube.com/watch?v=UOQ24PIcAYM&feature=youtu.be

**Crash Log:**

[crash-2019-07-29_21.46.42-client.txt](https://github.com/Cryptic-Mushroom/The-Midnight/files/3444854/crash-2019-07-29_21.46.42-client.txt)

**Comment by SmellyModder** [comment]
This is caused by another dimension's id being the same as Midnight's dimension id. You can change the id in the Mod's config.

**Comment by five0five** [comment]
Change the dimension id in the mod's config from -23 to 24 (or whichever number you like, but 24 should be available), the mod causing the conflict is fossils and archaeology

**Comment by ResidentCoder2** [comment]
Honestly, thank you both. I knew it had to do with that ID, I just never knew what it meant until now! :D
