### ISSUE TITLE
Crash due to being spawned on top of a rift when entering the midnight dimension. 

### ISSUE THREAD

**Issue by RavenRohr** [Cryptic-Mushroom/The-Midnight#261]
Using version 0.3.1 (the latest version for 1.12.2 as of a few weeks ago when I downloaded it). Basically if I enter a rift in the overworld and the location the mod decides to put me at also has a rift the game crashes and it becomes impossible to continue to play that world because you crash for the same reason every time you try to load the world after the initial crash.

**Comment by gegy1000** [comment]
Hi! Would you be able to share the crash report? :)

**Comment by RavenRohr** [comment]
I'll try and recreate the issue, both with the full mod set and with midnight on its own then send the reports as separate comments

**Comment by RavenRohr** [comment]
Crash log with other mods included:
https://paste.ee/p/4JiS8

**Comment by RavenRohr** [comment]
Crash with only midnight: 
[crash-2019-08-08_15.26.15-server.txt](https://github.com/Cryptic-Mushroom/The-Midnight/files/3483576/crash-2019-08-08_15.26.15-server.txt)

**Comment by gegy1000** [comment]
This should be fixed in the 1.14.4 port :)
