### ISSUE TITLE
Rift spawn only on night time in the Midnight dimension

### ISSUE THREAD

**Issue by Fireztonez** [Cryptic-Mushroom/The-Midnight#262]
Hello,
I really like your dimension, it is very different, and I like that! The only issue I have right now, is with the Rift spawn in the Midnight dimension. Currently, Rift spawn in the midnight only at Night Time, and on my modpack, the Day/night cycle is 3 time longer than usual minecraft day/time, so, when you want to go back to your base, sometime, you have to wait like 30 minutes for being able to see a single raft. This is very annoying and, I think, the fact of the dimension is "perpetual night", it should spawn at any time of the day.

I try to change the override the spawnrules of the midnight dimension using InControl and I can't get any spawn script working in your dimension. I try to make it spawn a lot of rift, nothing spawn using InControl... I try to spawn a lot of Rifter with the exact same way, still doesn't work. I change the mob to be `minecraft:cow`, still does't work. But, the same script if I change the dimension spawn about 2000 cow in a second!!!

If your want here's my potentionspawn.json from InControl!:
https://gist.github.com/Fireztonez/093df69cea52ff1fbaf05a4c71845dc9

**Version:**
The Midnight: 0.3.5
Forge: 1.12.2 - 14.23.5.2838

Thank's

**Comment by five0five** [comment]
We're overhauling the rift system on 1.14, but we no longer support 1.12, sorry :(

**Comment by Fireztonez** [comment]
Sincerly, you no longer support the current more used version for modpack?? This look like a pretty bad decision...

So, I can't do anything, I'm stuck with that problem?

**Comment by five0five** [comment]
You could use an external mod to create something a rift spawn egg, or an item that uses a command to summon a rift (/summon midnight:rift ~ ~ ~)

Forge 1.14 is very different to 1.12, and we only have 1 coder, it's a lot of work to maintain two versions in general, but especially for one person

**Comment by Fireztonez** [comment]
@five0five The Midnight is not even availiable right now for 1.14, and you stop the support for the only availiable version... Sincerly!!!

Do you think this is a great idea to do that... Do you think you will be support by modpack dev, if you stop supporting so fast your mod in the only availiable version question to try updating to the next version of minecraft??

**Comment by Fireztonez** [comment]
I can understand you have only one dev right now, and I know minecraft 1.14 is very different, but I think you should still try to fix the most important issue for 1.12... Is is soo complicated to change the spawn in the 1.12 version??

**Comment by gegy1000** [comment]
Yes
