### ISSUE TITLE
So I believe these two issues are related

### ISSUE THREAD

**Issue by CammiePone** [Cryptic-Mushroom/The-Midnight#264]
So what's happening is console is being spammed with this:
https://pastebin.com/76VMUTb5

Both have to do with the entity tracker, which is why I'm thinking they may be related.

EDIT: Turns out they are, and it's because of AI Improvements.
EDIT 2: Never mind, ignore edit 1. I now think that the two problems are independent of each other.

**Comment by gegy1000** [comment]
Hrm. This is a really weird bug, have gotten quite a few reports of it but can't ever seem to reproduce it. Makes it hard to track down 😄

**Comment by five0five** [comment]
if this occurs on 1.14, reopen
