### ISSUE TITLE
Crashing during nighttime

### ISSUE THREAD

**Issue by roultitude** [Cryptic-Mushroom/The-Midnight#266]
Been freezing up randomly during night time, sometimes recovering, sometimes resulting in a crash.

Either way produces the same crash log below.
Modpack being used is version 8.9 of Dimension Zero

Edit: Still occurs on the 9.0 version of DZ.

Crash Log: https://pastebin.com/NRJPPQdi

**Comment by five0five** [comment]
if this occurs on 1.14, reopen
