### ISSUE TITLE
No rift spawn

### ISSUE THREAD

**Issue by Khytwel** [Cryptic-Mushroom/The-Midnight#269]
Hey,

On the latest version for 1.14.4, I can't find any rift during the night. Yet, I've been through a lot of blocks, but it doesn't matter :/

I also increased the spawn rate, but that doesn't change anything.

Forge v28.0.45

**Comment by five0five** [comment]
I've found them, you might just be having bad luck

**Comment by Khytwel** [comment]
So I'm really unlucky because I've been flying around my world for more than 40 minutes with the night

**Comment by gegy1000** [comment]
Can try change the spawn rate to something like 1?

**Comment by Khytwel** [comment]
Yes, I'm going to test it
