### ISSUE TITLE
Miasma Interacts weirdly with other liquids

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/The-Midnight#27]
Miasma can overtake water if its below it, but water cannot overtake Miasma if miasma is below the water, causing if you were to put Miasma next to an ocean it will make its way down, but will not be deleted unless the source is deleted by a block or something, Miasma and Lava cannot overtake eachother in any way, meaning Miasma cannot overtake lava below it, and Lava cannot overtake miasma below it

**Comment by gegy1000** [comment]
Miasma interacting with other blocks should probably create solids, like water & lava do.

**Comment by Terenx** [comment]
Make make miasma surface when it contacts win lava, makes trenchstone when water is poured onto it and makes nightstone if miasma is poured onto water
