### ISSUE TITLE
Empty spots in creative tab

### ISSUE THREAD

**Issue by Lykrast** [Cryptic-Mushroom/The-Midnight#271]
The Midnight Building tab has 2 empty spots. No items are in there or can be gotten:
![image](https://user-images.githubusercontent.com/8684850/62939525-c99f8500-bdd1-11e9-9f4f-d8dd6b9eb739.png)

**Comment by gegy1000** [comment]
Well.. this is quite an interesting bug 😅

**Comment by gegy1000** [comment]
Fixed in https://github.com/Cryptic-Mushroom/The-Midnight/commit/fe05eb48d2e0b4631fe4e113c9c8de2dcd1a2fca for next release :)
