### ISSUE TITLE
[1.14.4] Server crash on loading with themidnight-0.4.1

### ISSUE THREAD

**Issue by ProsperCraft** [Cryptic-Mushroom/The-Midnight#273]
Relevant log section
https://gist.github.com/ProsperCraft/fde98b2eb5ce5e8ebe39fafa85e9e763

Crash log-
https://gist.github.com/ProsperCraft/3286eb56d8af9e6997232b4d388e340b

Modpack-
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by gegy1000** [comment]
thanks for the report. closed in https://github.com/Cryptic-Mushroom/The-Midnight/commit/257c410f973d8561b22473d8691b2e51f0e2ae8f
