### ISSUE TITLE
[1.14.4] Log spam with latest test build -

### ISSUE THREAD

**Issue by ProsperCraft** [Cryptic-Mushroom/The-Midnight#275]
I tried to close my console window on my client and it won't close - it is spamming

https://gist.github.com/ProsperCraft/2daa36642cf8c72f85698befe5d3159b

The log file is 284 megs after a short period of play.

**Comment by ProsperCraft** [comment]
[logs.zip](https://github.com/Cryptic-Mushroom/The-Midnight/files/3507133/logs.zip)

**Comment by ProsperCraft** [comment]
themidnight-0.4.2

**Comment by gegy1000** [comment]
Relates to #274: like I said there we can only semi-avoid it by making it not hard crash

**Comment by gegy1000** [comment]
Forge crashes when loading into the Midnight because the dimension registry isn't synced (and by this point it hasn't even gotten to our code yet)

**Comment by ProsperCraft** [comment]
I was able to get in to the dim and get out, everything seemed to be working fine aside from that log issue, which I fixed with the stuffasockinit mod which blocks logging if it matches the config.

**Comment by gegy1000** [comment]
If you log out of the server and log back in while in the dimension, it will break (well, it breaks anyway, this just breaks fatally)

**Comment by gegy1000** [comment]
Dirty hack to Forge code to fix until Forge does https://github.com/Cryptic-Mushroom/The-Midnight/commit/4f92c0be414e024b7b0b4bc76d76bd7660234db5
