### ISSUE TITLE
Crashing on 1.14.4

### ISSUE THREAD

**Issue by AyItsJayy** [Cryptic-Mushroom/The-Midnight#276]
The game crashed whilst initializing game
Error: java.lang.IllegalStateException: The ObjectHolder annotation cannot apply to a field that does not map to a registry. Ensure the registry was created during the RegistryEvent.NewRegistry event. (found : com.mushroom.midnight.common.biome.cavern.CavernousBiome at com.mushroom.midnight.common.registry.MidnightCavernousBiomes.CLOSED_CAVERN)

Edit: That's what was from the launcher, full crash-report here: https://pastebin.com/4qyyZEHF

I'm on the latest forge and mod version.

**Comment by gegy1000** [comment]
Thanks for the report; would you be able to send the full log too?

**Comment by AyItsJayy** [comment]
> Thanks for the report; would you be able to send the full log too?

https://pastebin.com/4qyyZEHF, sorry I didn't do it at first

**Comment by gegy1000** [comment]
Apparently this can occur if another mod errors before Midnight, and then Forge reports it as this. Does a different crash occur if you remove just Midnight, or have just Midnight installed?

**Comment by ProsperCraft** [comment]
Gegy is correct the problem lies in you trying to run mods that have not been updated to the breaking changes in forge .45, this is an hard to spot issue and took me 20+ hours to root out all mods that were not updated from my modpack.  Start with my adventures of Halk pack and which has 157 mods and works with Midnight and work from there adding one of your mods at a time if you like or just remove the mods you don’t want.

**Comment by AyItsJayy** [comment]
> Gegy is correct the problem lies in you trying to run mods that have not been updated to the breaking changes in forge .45, this is an hard to spot issue and took me 20+ hours to root out all mods that were not updated from my modpack. Start with my adventures of Halk pack and which has 157 mods and works with Midnight and work from there adding one of your mods at a time if you like or just remove the mods you don’t want.

Alright, I'll go down the error rabbithole. I did see your modpack and it inspired me to make my own after failed attempts at a big 1.14.4 modpack!

**Comment by AyItsJayy** [comment]
A quick update, the mod in question was RandomEnchants.
