### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by TheOhana** [Cryptic-Mushroom/The-Midnight#279]
hi guy's,
i have found an issue where the midnight doesn't even start when [upgrade Aquatic](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic) is installed maybe you can fix this? idk if its a problem on ur side or the others mod?!
[crash-2019-08-20_08.27.37-client.txt](https://github.com/Cryptic-Mushroom/The-Midnight/files/3519007/crash-2019-08-20_08.27.37-client.txt)

**Comment by five0five** [comment]
try updating your upgrade aquatic, you're on 1.0.4, the latest is 1.0.7

**Comment by TheOhana** [comment]
it does in deed sry for buggin you ^^
