### ISSUE TITLE
Portal to overworld

### ISSUE THREAD

**Issue by MelanX** [Cryptic-Mushroom/The-Midnight#28]
Is it possible to set the portal back to the overworld to a fix point? Because I wanna use this mod with SkyLands and now I traveled back home and fell down into the void :D 
My idea: You spawn where you entered the midnight world.

**Comment by gegy1000** [comment]
Not sure I fully understand the request -- currently rifts have a 1:1 mapping with coordinate in the Midnight vs coordinate in the Overworld.

**Comment by MelanX** [comment]
I played with SkyLands. So there is a lot of void. I traveled back to overworld and was falling into the void because there was nothing under me.
And my idea: You go through a portal to the Midnight. We name this point A.
You enter the Midnight and this is point B. And when travelling back you are back at point A. (yes, we don't need point B :D)
Is this description better? :)

**Comment by gegy1000** [comment]
Ah, I see. We definitely need to consider issues like this.

**Comment by Terenx** [comment]
Maybe try to make the rifts work like the new end portals, how when you go through em you always end up spawning in on solid ground

**Comment by Terenx** [comment]
but it should still be like the nether in the regard that traveling in the midnight would still change your position in the overworld, meaning you would come out in different areas.

**Comment by MelanX** [comment]
Solid ground sounds perfect. That’s the only reason I want this :D

**Comment by five0five** [comment]
is the solid ground issue fixed in the latest build?
