### ISSUE TITLE
Crashes when dimension loads

### ISSUE THREAD

**Issue by jounihh** [Cryptic-Mushroom/The-Midnight#280]
When the dimension tries to load it crashes the game. I tried this on a couple of worlds and it crashed on all of them. Also if you then try to load the world after you went into the dimension it crashes instantly.
This is on the ftb unstable 1.14 pack.

[crash-2019-08-20_17.35.08-client.txt](https://github.com/Cryptic-Mushroom/The-Midnight/files/3521196/crash-2019-08-20_17.35.08-client.txt)

[crash-2019-08-20_17.41.13-client.txt](https://github.com/Cryptic-Mushroom/The-Midnight/files/3521195/crash-2019-08-20_17.41.13-client.txt)
[latest.log](https://github.com/Cryptic-Mushroom/The-Midnight/files/3521198/latest.log)

**Comment by gegy1000** [comment]
This seems like an issue in another mod -- not clear which though. If you go travel into the nether does the same thing occur?

**Comment by jounihh** [comment]
Nether works fine. When i go the nether i get "The Midnight" achievement for some reason.

**Comment by jounihh** [comment]
[latest.log](https://github.com/Cryptic-Mushroom/The-Midnight/files/3521299/latest.log)

**Comment by gegy1000** [comment]
It is possible that the rich presence mod you have installed is causing the crash through the error it throws, but not certain.

**Comment by jounihh** [comment]
Yes disabling Simple Discord Rich Presence fixed it

**Comment by gegy1000** [comment]
Cool :)
