### ISSUE TITLE
Crash on 1.14.4

### ISSUE THREAD

**Issue by Wissi** [Cryptic-Mushroom/The-Midnight#289]
Love testing your mod. It has crashed our server with:
```
java.lang.IllegalStateException: The ObjectHolder annotation cannot apply to a field that does not map to a registry. Ensure the registry was created during the RegistryEvent.NewRegistry event. (found : com.mushroom.midnight.common.biome.cavern.CavernousBiome at com.mushroom.midnight.common.registry.MidnightCavernousBiomes.CLOSED_CAVERN)
```
Full log [here](https://gist.github.com/Wissi/f88c480ca7a2c86af4909d74f64b1013). 
Hope it helps.

**Comment by gegy1000** [comment]
This happens when another mod crashes due to not supporting Forge .45+. You can try isolate which mod is causing it by swapping them out

**Comment by Wissi** [comment]
Not sure how another mod is causing your mod to crash server. 
When your mod is reverted to ver 0.4.3 it works perfectly fine.

It seems that the registry is not being created for `com.mushroom.midnight.common.registry.MidnightCavernousBiomes.CLOSED_CAVERN`
``` 
Ensure the registry was created during the RegistryEvent.NewRegistry event. (found : com.mushroom.midnight.common.biome.cavern.CavernousBiome at com.mushroom.midnight.common.registry.MidnightCavernousBiomes.CLOSED_CAVERN)
```
but ok...

**Comment by Corail31** [comment]
@Wissi It's more related on how fml collects the errors, as the registry is not created but the holder still apply... for the custom registry and make a crash preventing to display the real error.
The only solution that i found for this (while doing tests about the mods incompatible with forge 45) was to create the registry in the mod constructor and not in RegistryEvent.NewRegistry.
Feel free to make your own tests with a custom registry and by adding a mod in a version incompatible to forge 45 ;)
