### ISSUE TITLE
Rockshroom blocks don't produce Rockshroom Clumps when broken

### ISSUE THREAD

**Issue by sqldiablo** [Cryptic-Mushroom/The-Midnight#291]
Using 0.4.4, when you break a Rockshroom Block, it drops an item of another Rockshroom Block instead of dropping Rockshroom Clumps, as the wiki suggests it should. We've tried all different types of pickaxes (vanilla, silent gear, and midnight), and nothing seems to produce the clumps.

**Comment by gegy1000** [comment]
This will be fixed in the next release :)
