### ISSUE TITLE
Rockshroom blocks don't drop clumps when mined. 

### ISSUE THREAD

**Issue by iceydragon88** [Cryptic-Mushroom/The-Midnight#294]
I am using 1.14.4. When I break rockshroom blocks, the clumps don't drop. I used all midnight picks and even open hand just to be sure. I love this mod but I can't progress without rockshroom clumps.

**Comment by five0five** [comment]
this is fixed indev, if you really need them you can find them via fishing in the dimension

**Comment by iceydragon88** [comment]
Thank you :D
