### ISSUE TITLE
Error Loading Up [1.14.4]

### ISSUE THREAD

**Issue by popcorndreams** [Cryptic-Mushroom/The-Midnight#295]
Every time I try to load up this mod, it says there was an error while loading. It gives me this dead link that leads nowhere: new/minecraftforge/fluids/FluidRegistry

I was REALLY looking forward to this mod, but this isn't this first time my computer has done this. Can someone tell me if its on the mods end or mine?

**Comment by littlett98** [comment]
Using forge version 28.0.45 should solve that issue. The mod is in the process of updating for newer forge versions but the build isn't released yet.

**Comment by popcorndreams** [comment]
Got it, thanks.

**Comment by gegy1000** [comment]
Forge's new fluid system isn't yet working properly, and we are awaiting a PR regarding that to be merged still. An update will be released to update as soon as possible :)
