### ISSUE TITLE
Strange console spam and crash on. 1.12.2

### ISSUE THREAD

**Issue by SirAron111** [Cryptic-Mushroom/The-Midnight#296]
Forge 14.23.5.2846
MC: 1.12.2

https://paste.dimdev.org/ijuyotesok.mccrash somehow mushroom.midnight.common.entity.RiftBridge.handleState
gets spammed from something and I can’t pinpoint it.
![Unbenannt](https://user-images.githubusercontent.com/39855956/64923559-11536b00-d7db-11e9-847e-4378a84bcfc3.PNG)

**Comment by Lewisking50** [comment]
Same for me.
Dimension Zero Modpack v9.2 +Optifine 1.12.2 HD U F2 pre1
Forge-Version: 14.23.5.2847
MC: 1.12.2
https://paste.dimdev.org/luvicebowo.mccrash

Removing Optifine seems to settle the issue...

**Comment by SirAron111** [comment]
https://www.twitch.tv/videos/486064696?t=1h22m18s is it not possible to fix this problem in any way??? vanillafix is just notifing people about it but since the error loops its actually pretty anyoing

**Comment by Jonathing** [comment]
The 1.12.2 version of The Midnight is no longer supported.
