### ISSUE TITLE
ItemColors Crash/Mod Compatibility

### ISSUE THREAD

**Issue by Darkfiend009** [Cryptic-Mushroom/The-Midnight#297]
Hey there!

Below are 2 crash reports and, while they look like they are caused by 2 different mods, there is a common factor between them. These crashes only appear if The Midnight is installed with either one of them. Without The Midnight present, they load just fine, even with both of them installed at the same time:

https://pastebin.com/SZttB5cP
https://pastebin.com/80qenYvp

This issue has been reported to the Nomadic Tents dev by another person:

https://github.com/skyjay1/Nomadic-Tents/issues/19

I will also report it to the Doggy Talents dev just to be thorough. Thanks for your time!

**Comment by Jonathing** [comment]
The Midnight for Minecraft 1.14.4 is no longer supported. If you believe that this issue still exists in the 1.15.2 version of the mod, feel free to reopen the issue and provide examples as to how that is.
