### ISSUE TITLE
Blocks/Items Missing Forge Tags

### ISSUE THREAD

**Issue by WenXin20** [Cryptic-Mushroom/The-Midnight#298]
Minecraft v1.14.4
Forge v28.1.10
Midnight v0.4.5

Midnight cobblestone, wood, and other blocks/items are missing their forge or minecraft tags for blocks and item drops. Both blocks and the corresponding items need a forge tag to be properly compatible with other mods.

Currently, this means that most recipes that use `#forge:cobblestone`, `#minecraft:planks`, or any others are not compatible with Midnight cobblestone, planks, etc.

See SilentChaos512/Silent-Gear#64 for a bit more info and the original post.

**Comment by five0five** [comment]
I'm not 100% but I believe this is intended, we have our own chests, sticks, etc. that would craft the vanilla chest if our planks used #minecraft:planks

**Comment by WenXin20** [comment]
Alright. If it's intended, I'll go ahead and close this.
