### ISSUE TITLE
No echo or fog in the midnight dimension on my personal server

### ISSUE THREAD

**Issue by Silails** [Cryptic-Mushroom/The-Midnight#299]
Hi, so I was hyped to show this mod to my friend, but when we entered the dimension, I was sad to see that there was no echo or fog in the dimension.
While the mod works perfectly with all the other mods I use in solo, the server with the same mods (without the client only mods) doesn't get the coolest effects
On a server with only the midnight dimension, it works, so maybe it's a compatibility issue with a mod that has unique features on servers only? I'll look into that on my side and be back with updates on my situation.
Here's the full log of the server (with redacted ip): https://pastebin.com/FB9aqMfk
Thank you for taking the time to read my issue

Update1: it's not a compatibility issue, I created a new world with all the same mods, and everyting worked just fine, it probably is because I added the midnight dimension on a already created world
    -dumb things I tried: 
Rebuilding a new world with the same seed and copying the region data from the overworld and the nether from the old "world" to the new one didn't work probably because of reasons my peasent brain can't understand.
Changing the dimension id so that midnight is the 3rd one
Update2: so I'm currently adding the mods back 1 by 1 to see whose to blame, and when I added biom's o plenty back, the midnight grass turned green, what?

**Comment by gegy1000** [comment]
If you have any other mods installed that add dimensions, those might be responsible for breaking the dimension

**Comment by Silails** [comment]
> If you have any other mods installed that add dimensions, those might be responsible for breaking the dimension

sadly, deleting good night sleep (the only other dimension installed) didn't fixed the issue

**Comment by Silails** [comment]
> If you have any other mods installed that add dimensions, those might be responsible for breaking the dimension

Hmmmm but by adding back the mods 1 by 1, not adding good night sleep back fixes the issue, but it adds an other one, having Biome's o plenty makes the midnight purple grass into a green colored grass (still midnight grass)

**Comment by Silails** [comment]
> > If you have any other mods installed that add dimensions, those might be responsible for breaking the dimension
> 
> Hmmmm but by adding back the mods 1 by 1, not adding good night sleep back fixes the issue, but it adds an other one, having Biome's o plenty makes the midnight purple grass into a green colored grass (still midnight grass)

OK, first sorry for the spam, but changing the world back to the "old" one (the backup before doing anything) and not having good night sleep on fixes everything!
