### ISSUE TITLE
Execution Exception

### ISSUE THREAD

**Issue by EndangeredProdigy** [Cryptic-Mushroom/The-Midnight#303]
https://gist.github.com/Jonathing/6007458dae125cf4ed9afb7aa2be43e8

**Comment by FenixFyreX** [comment]
Just got this same error playing FTB Unstable 1.14 (forge 1.14.4-28.1.109, midnight 0.4.6). Any clue on a fix? It hard froze the server, and I had to force close it.

**Comment by Jonathing** [comment]
I don't know why Midnight is causing this. One possible issue is that you're trying to load it with the FTB Unstable modpack, which might cause some issues. I'll look into this at a later time.

**Comment by dbulm2** [comment]
this happens on MCEternal (1.12.2) for both me and a friend. Identical log except line 24-26
`    at com.mushroom.midnight.common.network.MessageBridgeState$Handler$$Lambda$8356/926365410.accept(Unknown Source)
    at com.mushroom.midnight.client.ClientProxy.lambda$handleMessage$1(ClientProxy.java:39)
    at com.mushroom.midnight.client.ClientProxy$$Lambda$8355/1219156328.run(Unknown Source)`

**Comment by Jonathing** [comment]
@dbulm2 We don't support The Midnight for 1.12.2 anymore. Read the README.md file for more info.

**Comment by dbulm2** [comment]
I know, I didn't want help with it, just pointing out that it's been an issue for longer, in case it helped.

**Comment by dbulm2** [comment]
An interesting development, Removing Midnight for my problem (the game freezing constantly after a few hours) didn't fix it, the error is just a symptom of the freeze.

**Comment by PepoooCrack11** [comment]
> An interesting development, Removing Midnight for my problem (the game freezing constantly after a few hours) didn't fix it, the error is just a symptom of the freeze.

Man, sorry for my ignorance but what do you mean by "freeze" i have experienced the same issue recently and just encountered that v1.12.2 doesn't have support anymore, such a shame..

**Comment by Jonathing** [comment]
As I stated earlier, we aren't supporting the older versions of The Midnight. I'm sorry that they're a huge mess but it's not worth going back to older Minecraft versions to fix something that's already been abandoned.
