### ISSUE TITLE
Suggestion: Improved hitboxes for Rifters

### ISSUE THREAD

**Issue by QuantumToasted** [Cryptic-Mushroom/The-Midnight#308]
Hello! I have noticed that hitboxes for Rifters seem to be inconsistent with their bodies compared to, say, a Zombie or Skeleton. I'm sure this likely could be some wonkiness with custom entities.

I seem to have trouble getting hits to connect at ranges where it *looks* like it would otherwise connect with the body compared to other mobs, as well as having trouble getting them to connect with higher and lower portions of their bodies such as heads and legs. Aiming for a specific portion of their torso seems to be the only way to get a hit in.

Would this be something worth looking into?

**Comment by Jonathing** [comment]
Yeah, I've noticed that too. I'll get to work on it soon.

**Comment by RedGalaxySW** [comment]
This is fixed in 0.4.7 and 0.5.5
