### ISSUE TITLE
Crash log playing on a server.

### ISSUE THREAD

**Issue by buuns** [Cryptic-Mushroom/The-Midnight#310]
Having an issue where if I let night time roll around your mod causes my ram usage to sky rocket past what I've set and eventually freezes up my entire system. Crash report below

[https://pastebin.com/chCPk1Lc](https://pastebin.com/chCPk1Lc)

**Comment by Jonathing** [comment]
The server seemed to have crashed because it couldn't load the shaders from the mod. I'm marking as on hold for now as we have a bigger issue at hand, but I'll check back on this and see what I can find.

**Comment by Jonathing** [comment]
The Midnight for Minecraft 1.14.4 is no longer supported. If you believe that this issue still exists in the 1.15.2 version of the mod, feel free to reopen the issue and provide examples as to how that is.
