### ISSUE TITLE
Texture issue: Possible incompatibility

### ISSUE THREAD

**Issue by OHKOBunny** [Cryptic-Mushroom/The-Midnight#312]
Hello I'm currently using the most recent version for 1.12 and having a bit of a missing texture problem: https://cdn.discordapp.com/attachments/492466817915289600/631980797317873676/unknown.png

It's exclusively the little ground mushroom, any idea what could be causing such an issue? I tried disabling Better Foliage as I thought that may be what's causing the trouble but it turns out it wasn't that.

**Comment by five0five** [comment]
betterfoliage does cause that same issue, try removing it again and make sure its not present

**Comment by OHKOBunny** [comment]
Do you know which part of it causes the issue? I'd rather disable that bit than lose the fluffy trees all together

**Comment by five0five** [comment]
pretty sure its not configurable but someone else might know otherwise

**Comment by OHKOBunny** [comment]
Okay yeah it wasn't something I could turn off, is this something that can be fixed? BF works fine with other mods and I have no idea why it'd be having troubles here..

**Comment by five0five** [comment]
its because the textures are emissive, its an issue on their side and the issue has existed for ages so I doubt it will be fixed

**Comment by DuckODestiny** [comment]
Had this same problem but found a work-around by setting the mipmap level to 0

**Comment by cybercatgurrl** [comment]
I had the same issue. Disabling better foliage fixed it as well.

**Comment by Khanbit64** [comment]
> pretty sure its not configurable but someone else might know otherwise

Better foliage is configurable, however, after blacklisting all the missing texture blocks, nothing changed

**Comment by Jonathing** [comment]
We will no longer be updating the 1.12.2 version of The Midnight. https://www.minecraftforge.net/forum/topic/79304-112114-and-lts-system/
