### ISSUE TITLE
Rifter spawn issues in Midnight dimension [1.14.4]

### ISSUE THREAD

**Issue by noobanidus** [Cryptic-Mushroom/The-Midnight#318]
In addition to the considerable amount of health and armor (plus the 2x multiplier from being in the Midnight), packs of Rifters might not do a huge amount of damage (although that has a 3x multiplier from being in the Midnight). The main issue is that, after coming through my very first portal, I was set upon by a pack of at least six:

![](https://i.imgur.com/3fKA7cF.jpg)

When I made it back to my grave after finally using Creative, `/forge entity list` reported:

![](https://i.imgur.com/hcguaFk.png)

I used `/kill @e[type=midnight:rifter]` to clear the area so I could go back into survival and retrieve my items; 11 rifters were killed. After I had re-equipped my gear, I ran `/forge entity list` again (keeping in mind that I was the only one in the dimension hence this was all in chunks next to me):

![](https://i.imgur.com/Ya3HLoA.png)

Due to slight server lag I was barely able to hit them let alone run away from them, and the fact that they hardly seemed to take any damage, had a decent amount of health & were quite fast to boot, they seem ridiculously unfair.

Scrolling through the entity code itself I noticed:

```java
    @Override
    public int getMaxSpawnedInChunk() {
        return 1;
    }
```

This appears to do nothing.

**Comment by Jonathing** [comment]
The Midnight for Minecraft 1.14.4 is no longer supported. If you believe that this issue still exists in the 1.15.2 version of the mod, feel free to reopen the issue and provide examples as to how that is.
