### ISSUE TITLE
Rifters taking damage does not stop them from kidnapping you (1.14)

### ISSUE THREAD

**Issue by noobanidus** [Cryptic-Mushroom/The-Midnight#319]
In addition to my previous issue, I hit a Rifter that was attempting to kidnap me twice with a diamond sword, and it didn't drop me. 

I think further to the entity being kidnapped, you could look at adjusting the player's view to be directly facing the Rifter, instead of having to rotate your camera around to find out where the thing is in the first place.

**Comment by Jonathing** [comment]
The Midnight for Minecraft 1.14.4 is no longer supported. If you believe that this issue still exists in the 1.15.2 version of the mod, feel free to reopen the issue and provide examples as to how that is.
