### ISSUE TITLE
Reverb doesn't work after reload.

### ISSUE THREAD

**Issue by JacksonPlayz** [Cryptic-Mushroom/The-Midnight#320]
While in the Midnight dimension, the reverb seems to break on resource pack changes, F3+T, or anything that reloads sounds / the game. Block breaking sounds stop working, entity sounds stop working, pretty much anything that is affected by the reverb no longer has any audio.

**Comment by JacksonPlayz** [comment]
I should also note that when going back into another dimension, all audio is broken there too, same thing applies.

Reloading seems to break the entire sound engine in general.

**Comment by JacksonPlayz** [comment]
I should also note that when going back into another dimension, the audio is also broken. Reloading seems to break the entire sound engine in general.

**Comment by gegy1000** [comment]
What Minecraft version is this in?

**Comment by JacksonPlayz** [comment]
1.14.4, I'm using the latest file on CurseForge

**Comment by gegy1000** [comment]
Cool, thanks for the report :+1:
