### ISSUE TITLE
[bug/feature] Dark Water does not use 1.13 mechanics

### ISSUE THREAD

**Issue by BardGitH** [Cryptic-Mushroom/The-Midnight#324]
![2019-11-17_18 01 54](https://user-images.githubusercontent.com/57300546/69010870-5d9a6300-0964-11ea-8308-50123a6f07db.png)

Dark Water from The Midnight does not waterlog like vanilla water does since the 1.13 update.

**Comment by RedGalaxySW** [comment]
This is possibly hard to get. I have it in another mod but it causes compatibility issues and a lot of work as we need to rewrite all the slab, stair and fence blocks to use both dark water and vanilla water... Once Mojang has completely separated fluids from blocks and we are updated to that version we will support it :)

**Comment by Jonathing** [comment]
Closing this because we're removing Dark Water lmao
