### ISSUE TITLE
Vignette effect appears in overworld

### ISSUE THREAD

**Issue by BardGitH** [Cryptic-Mushroom/The-Midnight#325]
version used: themidnight-0.4.6.jar

![2019-11-21_15 54 33](https://user-images.githubusercontent.com/57300546/69349051-6bf3c200-0c77-11ea-953b-a21295445a6d.png)

the effect only dissapears after entering the midnight and leaving again

**Comment by gegy1000** [comment]
Hmm, this is weird. Try toggling the 'hide vignette effect' config option

**Comment by BardGitH** [comment]
still an issue, except this time it seems to pop in and out of existence every so often when leaving the midnight for a few minutes, after which is stabilizes and no longer becomes a problem. The only 100% way of removing it is killing myself and respawning

**Comment by gegy1000** [comment]
Do you have any other mods installed?

**Comment by SmellyModder** [comment]
That looks like Upgrade Aquatic's Insomnia overlay. Do you have it installed?

**Comment by BardGitH** [comment]
yes i do, that must be it, thanks :)

**Comment by gegy1000** [comment]
Ah! That makes sense :)

**Comment by five0five** [comment]
just wanna mention you can turn it off in the config and it will be off by default next update @BardGitH
