### ISSUE TITLE
Can't collect mushroom caps with silk touch

### ISSUE THREAD

**Issue by Shreddys** [Cryptic-Mushroom/The-Midnight#326]
I don't know if it is intended or not, but you can't collect mushroom cap blocks with silk touch (like you can with vanilla giant mushrooms).

Minecraft 1.14.4
Forge 28.1.88
Midnight 0.4.6

**Comment by Jonathing** [comment]
This might have to do with the update to Forge 31.2.0, but you are now able to collect bogshroom cap blocks with a silk touch pickaxe.
