### ISSUE TITLE
Bugged Worldgen after leaving the Midnight

### ISSUE THREAD

**Issue by Shreddys** [Cryptic-Mushroom/The-Midnight#328]
After spending a protracted amount of time in the Midnight I left through a rift that had opened in the cave networks underground. When I came out in the overworld I was in previously ungenerated chunks out in the ocean. The nearby islands ended up being generated as black_ridge biomes, with nightstone laid out on top of the overworld blocks with mushrooms scattered about. An interesting effect to be sure, but the bug also froze entities in place and prevented me from interacting with them or flying with the elytra (but not swimming, oddly enough). I reloaded the save and the error persisted.

Edit: I forgot to mention, when I tried to save and quit Minecraft, it got stuck on the "Saving World" screen, so I had to kill the client.

Minecraft 1.14.4
Forge 28.1.88
Midnight 0.4.6

**Comment by gegy1000** [comment]
Interesting.. this is very odd! Do you have any other mods installed? Wonder if it's a strange interaction between mods

**Comment by Shreddys** [comment]
I have a handful of mods that change worldgen in some way or another. Biomes O' Plenty, Quark, Druidcraft, forbidden arcanus, mystical world, extended caves, and ... I think that's it?

Loss of functionality aside, the effect was pretty neat. Kind of like the midnight was encroaching into the overworld, with tall spires of nightstone, dotted with mushrooms and other flora.

**Comment by gegy1000** [comment]
This may relate to another issue report, where it was reported to be caused by Biomes O' Plenty. Are you able to reproduce it if you temporarily remove BoP? :)

**Comment by Exrom934** [comment]
I have had the same issues with world gen. I also have Biomes O' Plenty but didn't have an issue until recently loading new chunks will be Black_Ridge like he said. Unlike him it wasn't from me coming out and changing the terrain mine was just from flying into new chunks with elytra and them generating like that.

**Comment by Shreddys** [comment]
I haven't tested if it still happens if I remove BoP. But I suppose I should add a little more information. I was on that worldsave for a fair amount of time (explored the Nether, the End, etc) and the bug only showed up after I entered and exited the Midnight the first time. The aforementioned 'protracted amount of time' was during my first visit to the Midnight.

**Comment by Exrom934** [comment]
Tested Removing midnight all together and it removed all the blocks from the world with not complications. Some of the world gen wasn't even on top of a biome, it was just a midnight mountain in the middle of an ocean that has now disappeared. 

Gonna test putting it back in later and seeing if it persists/Regens the previous terrain again.

**Comment by jajaperson** [comment]
I'm getting biome conflicts with Biome Bundle. Is there a way to change the biome IDs in config?

**Comment by Jonathing** [comment]
The Midnight for Minecraft 1.14.4 is no longer supported. If you believe that this issue still exists in the 1.15.2 version of the mod, feel free to reopen the issue and provide examples as to how that is.
