### ISSUE TITLE
[feature] I have a feeling there are supposed to be more aggressive mobs.

### ISSUE THREAD

**Issue by TelluriumElecto** [Cryptic-Mushroom/The-Midnight#329]
The only ones that are spawning are the Rifters, and they spawn very rarely. I am on hard mode. Is there a setting I need to change to fix this?

**Comment by five0five** [comment]
there should be hunters in barren biomes, snappers in dark water, novas and stingers underground

mods sort of broken rn in general so

**Comment by Winddbourne** [comment]
I had noticed a lack of hostile mobs compared to the erebus or (especially) the Atum.  I'm not sure if this is intended though since you can reach the dimension so much earlier than even the Nether; night one if you want.

**Comment by Jonathing** [comment]
One major thing we are taking into account for the rewrite is making The Midnight much more aggressive. We'll take this issue into account as well.
