### ISSUE TITLE
certain mods screw up the spawns in the midnight

### ISSUE THREAD

**Issue by gravysamich** [Cryptic-Mushroom/The-Midnight#330]
an example being [wendigoism](https://www.curseforge.com/minecraft/mc-mods/wendigoism)

it seems like wendigoism is overwriting spawns of other mobs so all i am seeing is rifters and wendigos. honestly, i don't mind seeing the wendigos as it makes a certain sort of sense that they would live there, but i feel like i am missing out on all the other mobs.

if this issue does get fixed, i would still like the option to allow wendigos to spawn there, but still see the other mobs

**Comment by Jonathing** [comment]
This issue is vague and has been inactive for a chunk of time. To add on the mob spawns, it is most likely a problem on the developer's side, as midnight controls the spawn rate of its own mobs.
