### ISSUE TITLE
[Feature Request] Add config option to prevent Rifters from capturing name-tagged entities.

### ISSUE THREAD

**Issue by Vaelzan** [Cryptic-Mushroom/The-Midnight#332]
Similar to the existing option to prevent Rifters from capturing tamed entities, I think it would be a huge quality of life increase to be able to prevent them from capturing name-tagged entities too. It's hard breeding up replacement pandas with the same personality as the old ones! I can see this sort of thing being useful for others too.

For now I've blacklisted pandas in general from being taken, but I think it would make more sense for wild animals to be taken but named animals to be left alone, in the same manner as tamed ones.

**Comment by Vaelzan** [comment]
I should add that I'm happy enough to code and submit a patch implementing this change too if you want, I just don't want to do it until given the go-ahead since I don't want the effort to be wasted. :)

**Comment by RedGalaxySW** [comment]
Don't waste your time anymore...
This is added with the next 1.15.2 patch but NYI as the rifter capturing ability is still waiting for re-evaluation. Once that is done it will have effect...
