### ISSUE TITLE
Texture render issue

### ISSUE THREAD

**Issue by skyeblueocean** [Cryptic-Mushroom/The-Midnight#336]
I’m having textures show up as the black/pink blocks. I disabled Better Foliage as per someone else’s report but it only fixed half of my errors. Any other mods that would do this?

**Comment by Khanbit64** [comment]
Same here!

**Comment by Jonathing** [comment]
This issue is vague and has been inactive for a chunk of time. Re-open if the issue still exists and be more specific, please.
