### ISSUE TITLE
Missing Wood Recipes

### ISSUE THREAD

**Issue by WenXin20** [Cryptic-Mushroom/The-Midnight#338]
`Minecraft v1.14.4`
`Forge v28.1.109`
`Midnight v0.4.6`

Shadowroot and others logs are missing the 4 logs to 3 wood recipes.

Tags are also missing for logs, for example, shadowroot would be `midnight:shadowroot_logs`.
This will allow recipes to reference that tag to include the 4 different variants, the log, wood, stripped log, & stripped wood.

**Comment by Jonathing** [comment]
I do not plan on adding new features and enhancements to the 1.14.4 version of The Midnight. Any new features can be found on the 1.15.2 branch.

**Comment by WenXin20** [comment]
That's fine, I've already moved to 1.15.2 anyway.
