### ISSUE TITLE
Missing Textures For Plants [1.12.2]

### ISSUE THREAD

**Issue by Doom1991** [Cryptic-Mushroom/The-Midnight#339]
Most of the mushroom plants are showing up as missing textures. I've disabled Optifine to see if it would fix the issue but it did not. Nightshroom shows as a missing texture as a block but not as an item icon. Tall Dewshroom shows up as an item icon but not for both its top block and bottom block. None of my other mods have issues nor should cause issues like this but it seems like this mod has a lot of conflicts with other mods as seen in other bug reports on here for this mod. This mod looks cool but sure as hell isn't worth disabling every other one of my mods for it (Nor any for that matter). Big RIP for this...

**Comment by gegy1000** [comment]
This is an issue in Better Foliage :)

**Comment by Khanbit64** [comment]
> This is an issue in Better Foliage :)

Could you help to fix it?

**Comment by DamienBrittan** [comment]
> > This is an issue in Better Foliage :)
> 
> Could you help to fix it?

Do you steel need help ? Try to increase Minimap Levels to :OFF .

**Comment by Jonathing** [comment]
We will no longer be updating the 1.12.2 version of The Midnight. https://www.minecraftforge.net/forum/topic/79304-112114-and-lts-system/
