### ISSUE TITLE
You can plant crops in midnight grass/midnight dirt, no tilling required

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/The-Midnight#34]

**Comment by gegy1000** [comment]
Screenshot from #58:
![screenshot](https://user-images.githubusercontent.com/44714743/47944691-49242d80-defd-11e8-8882-91ee888e21d2.png)

**Comment by gegy1000** [comment]
Is this still an issue?

**Comment by five0five** [comment]
it is, iirc
