### ISSUE TITLE
Inventory deleted when Midnight Shadowroot chest is converted to Iron/Copper Chest

### ISSUE THREAD

**Issue by happybandit360** [Cryptic-Mushroom/The-Midnight#341]
## Version Information
`Minecraft: ` 1.12.2
`Forge: ` 14.23.5.2838
`Midnight:` 0.3.5
`Iron Chests: ` 1.12.2-7.0.67.844

## Summary
When a Shadowroot chest (from the Midnight mod) is converted to Iron Chests using with the Wood to Iron or Wood to Copper upgrade, the chest's inventory is deleted. This is the only chest in our pack this happens with. This report is also being filed with the Iron Chests dev. Here is a Twitch clip of the issue occurring - https://clips.twitch.tv/OptimisticAgreeableRatPlanking

## Steps to Reproduce
1) Place Shadowroot chest
2) Add items to chest inventory
3) Convert chest to Iron Chests mod using either Wood to Iron or Wood to Copper upgrade
4) Open chest to see inventory gone.

**Comment by Jonathing** [comment]
We will no longer be updating the 1.12.2 version of The Midnight. https://www.minecraftforge.net/forum/topic/79304-112114-and-lts-system/
