### ISSUE TITLE
When I kill The Rifter while he grabs me, my movement becomes slow and my character remains on the ground.

### ISSUE THREAD

**Issue by Kurogos** [Cryptic-Mushroom/The-Midnight#343]
When The Rifter stops grabbing me, my character remains on the ground and my movespeed is severely reduced, permanently (or until I die and respawn).

I'm also using MoBends, I don't know if it interferes.

Ver 1.12.2 (Forge)

**Comment by Jonathing** [comment]
We will no longer be updating the 1.12.2 version of The Midnight. https://www.minecraftforge.net/forum/topic/79304-112114-and-lts-system/
