### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by Severynn99** [Cryptic-Mushroom/The-Midnight#345]
I use quite some mods, but who doesn't? I'm not sure if this is an incompatibility issue, or something else, but it just won't launch. It says the issue is this mod. It's 1.12.2

Here's the crash report:

https://paste.dimdev.org/okusuratuc.mccrash

**Comment by fivelol** [comment]
change the dimension id (from -23) in the config file

**Comment by Severynn99** [comment]
> change the dimension id (from -23) in the config file

Change it to what?

**Comment by fivelol** [comment]
try uh 46, if that doesn't work, try again, its just a matter of finding an id that a dimension doesn't already use

**Comment by Severynn99** [comment]
> try uh 46, if that doesn't work, try again, its just a matter of finding an id that a dimension doesn't already use

Ah that fixed it, thank you!
