### ISSUE TITLE
The Midnight Error 

### ISSUE THREAD

**Issue by heiseshuishan** [Cryptic-Mushroom/The-Midnight#347]
https://paste.ubuntu.com/p/gxQtZQSQHt/

**Comment by NLBlacky** [comment]
Having the same error spammed in our console. This is with version _themidnight-0.3.5.jar_ on a server running the modpack MC Eternal version 1.3.2.

**Comment by catchra** [comment]
i was afk and VanillaFix pop up and said The Midnight crashed and gave me this link [https://paste.dimdev.org/yayemovomu.mccrash](url)

**Comment by pixelblob** [comment]
same problem here

**Comment by Jonathing** [comment]
This issue seems to be for 1.12.2. As stated on the CurseForge page, we will no longer be updating the version for that version of Minecraft. I will try to see if the problem can be reproduced in the latest version for 1.15.2. If not, I will close this issue.

**Comment by Jonathing** [comment]
The pastebins that were originally attached to the issue are no longer visible, so I will be closing this issue.
