### ISSUE TITLE
Rift spawns on Mushroom Island

### ISSUE THREAD

**Issue by scribbler957** [Cryptic-Mushroom/The-Midnight#348]
The mushroom island is supposed to be a safe place, but the rift spawns there anyway.

**Comment by Jonathing** [comment]
I will fix this issue once the rift is re-added into the latest 1.15.2 version.

**Comment by Jonathing** [comment]
I'll mark this is as an issue. We're rewriting the rift portal and we'll make sure it doesn't spawn in the mushroom island. If I release a bugfix patch for 1.14.4, I'll try to include that as well.

**Comment by Jonathing** [comment]
This issue has been fixed and will be released in a bugfix update for 1.14.4.
