### ISSUE TITLE
Midnight dimension has no bedrock

### ISSUE THREAD

**Issue by RedGalaxySW** [Cryptic-Mushroom/The-Midnight#350]
The world generator code seem to specify that bedrock _is_ generated but the only thing I find below the world are a couple of caves leading into the void and just regular Nightstone (with ores).  Seems to be a bug.

Line that specifies bedrock generation:
https://github.com/Cryptic-Mushroom/The-Midnight/blob/1.14.4-dev/src/main/java/com/mushroom/midnight/common/world/MidnightChunkGenerator.java#L113

Weird enough, Miasma lakes seem to have the bedrock pattern on the floor, but then made of just Nightstone...

Afaik this bug is already known but here's an issue ticket anyways.

**Comment by Jonathing** [comment]
Really? At first, I thought that was intentional, but I haven't been around for much in recent times.

**Comment by Jonathing** [comment]
Broken Item: Fixed.
