### ISSUE TITLE
Hunter flying into oblivion

### ISSUE THREAD

**Issue by Frenderman** [Cryptic-Mushroom/The-Midnight#357]
Hunters spawned naturally or summoned fly up diagonally and dont stop

**Comment by Jonathing** [comment]
![The hunters flying off into the sunset.](https://cdn.discordapp.com/attachments/495315724911509533/692543936731938906/2020-03-26_10.22.04.png)

**Comment by pentantan** [comment]
fixed hunter flying ai
[https://github.com/Cryptic-Mushroom/The-Midnight/commit/b659d27b03245d6054911368baac42ee3ecec6e6](url)
