### ISSUE TITLE
Silent gems and The Midnight crash.

### ISSUE THREAD

**Issue by soswi** [Cryptic-Mushroom/The-Midnight#361]
1.15.2

The Midnight 0.5.1
Silent's Gems 3.5.1
Forge 31.1.25

I'm trying to run a server with Silent Gems and The Midnight mod, but it's crashing. I asked your support what is happening and they sad that silent gems don't now if riffis in the game (created by Midnight) should has a soulgem or not. That's why it's crashing. I'm adding a crash log so u can see.

What can I do in order to make it work ?
[crash-2020-03-24_23.14.46-server.txt](https://github.com/Cryptic-Mushroom/The-Midnight/files/4388201/crash-2020-03-24_23.14.46-server.txt)

I posted it here and on SilentGems Issues

**Comment by Jonathing** [comment]
We released a new update for The Midnight that fixes this issue. You can download it from [the CurseForge page](https://www.curseforge.com/minecraft/mc-mods/the-midnight/files/2913047) or [the release on GitHub](https://github.com/Cryptic-Mushroom/The-Midnight/releases/tag/0.5.1).
