### ISSUE TITLE
Maligant bridging and hanging vines texture problem 1.15.2

### ISSUE THREAD

**Issue by FrimPvP** [Cryptic-Mushroom/The-Midnight#368]
![2020-03-31_22 37 45](https://user-images.githubusercontent.com/62962144/78068009-5e2a1800-73a0-11ea-8634-c85197480117.png)

I think this image tells everything. Part of the texture are white and i think its supposed to be not white.

**Comment by Jonathing** [comment]
![https://i.imgur.com/mKBCATl.png](https://i.imgur.com/mKBCATl.png)
Fixed.
