### ISSUE TITLE
Cannot get to the dimension through the gate 1.15!!

### ISSUE THREAD

**Issue by FrimPvP** [Cryptic-Mushroom/The-Midnight#369]
So what happened to me that earlier this mod worked just fine and I had so much fun playing this mod!
Now when I opened minecraft and I went to the world and suddenly the gate way portal didn't work anymore for somehow.
I tried creating a new world, restarting the game, deleting the mod and downloading it again but doesn't seem to work.
I have video evidence of what happened but zip file is too large for this website. I am in the discord server so you can dm me, my name in the server is Frim

**Comment by FrimPvP** [comment]
I would like to add that the block is somehow a still block what you can walk on.

**Comment by FrimPvP** [comment]
Ok i've uploaded video to the google drive here is the link
https://drive.google.com/file/d/1DyQlAq0_SBkcAEf4fBDHr6hVJhmjeoLA/view?usp=sharing

**Comment by Jonathing** [comment]
The midnight portal only spawns at nighttime.
