### ISSUE TITLE
Suavis Block causing crash with both vanilla fish mobs and other mod's mobs

### ISSUE THREAD

**Issue by TelepathicGrunt** [Cryptic-Mushroom/The-Midnight#372]
Hello! It seems the Sauvis Block is causing a crash with various mobs due to line 171 being ` return world.getBlockState(pos).get(STAGE) < 2;` instead of `return state.get(STAGE) < 2`:
https://github.com/Cryptic-Mushroom/The-Midnight/blob/f7867737e4a95ac1824c40798f91133a8dac6518/src/main/java/com/mushroom/midnight/common/block/SuavisBlock.java#L171

Originally, a user found that the crash occurred with The Endergetic Expansion when their Puff Bug mob is spawned near a Sauvis Block. So I reported the issue to Endergetic Expansion butshortly afterwards, the mod author found that the issue was caused by the Sauvis Block with that line of code above inside. And that the crash can also be reproduced by placing the Sauvis block underwater with Vanilla fish around. 

The full explanation for the bug can be found here: https://github.com/minecraftabnormals/The-Endergetic-Expansion/issues/28#issuecomment-608086921 

I hope this helps!

**Comment by pentantan** [comment]
Thank you for telling me about the crash!
This problem was fixed immediately↓
https://github.com/Cryptic-Mushroom/The-Midnight/commit/128a15f5272d947c19b672e2d858c969402ffa75
