### ISSUE TITLE
[bug] Server hang with midnight biome in the overworld

### ISSUE THREAD

**Issue by Thenardite** [Cryptic-Mushroom/The-Midnight#377]
So, I can't really find info about this anywhere, but... The only way to get to the midnight is the rift, right?  Or can a chunk or two just generate in the overworld? If no, what's the problem?

I play 1.15.2 modded survival (including Biomes O'Plenty and Biomes You'll Go) and while travelling I stumbled upon a midnight-generated biome (midnight:vigilant_forest), complete with mobs, plants and stuff. Once I near it, I get THE extreme lag: I can'td ismount a boat, blocks or items don't drop anything when destroyed, mobs move only for a little and then remane stuck in a one position, chunks outside of those generated around my current position stop loading even if I passed there before, can't interact with items like book and quill etc. Even opening world for LAN and testing cheats (changing time, gamemode etc) doesn't work - they have no effect, even though the chat says that they were used. 
To leave the game I have to kill the game process from a task manager, otherwise "Saving world" is shown indefinitely. It DOESN'T CRASH, it freezes on exit. When I load the world back, I spawn some distance away from a place it begins to lag on, with everything working fine, but then, if I move there again, everything breaks again.
The nearest biome is a giant vanilla ocean, no mod biomes around.

I've tried to lower my video settings, thought that maybe my PC just isn't up for it, but even on the most minimal settings possible it still does the same thing. And then I realized that there was no rift around, I just straight up swam into a biome's water, and thought that it just might be not how it's supposed to be.

Can't figure out how to attach a screenshot as a proof, so attaching a latest.log+debug.log, if needed:
[debug.log](https://github.com/Cryptic-Mushroom/The-Midnight/files/4456770/debug.log)
[latest.log](https://github.com/Cryptic-Mushroom/The-Midnight/files/4456771/latest.log)

**Comment by IchigoGames** [comment]
same thing happen to me on my modpack

**Comment by IchigoGames** [comment]
also and ill report this as a bug in a min but in the biome in converted into a midnight dim biome it was spawning thos purple silverfish looking mobs without limit had over 5k of the droped tps two 2

**Comment by JLS-cs** [comment]
prolly got the same :(

**Comment by Jonathing** [comment]
Unfortunately, the logs you posted don't help that much as all they say is that the server couldn't keep up. Most of the debug log is just the game starting up.

**Comment by ShadewRG** [comment]
I've seen this issue ocurring in the midnight itself once entities walk out of a loaded chunk - into an overworld biome (unloaded chunks always have plains biome). Not yet confirmed but probably reproducable by placing mobs in the overworld...

**Comment by Jonathing** [comment]
Closing for now as we are rewriting the mod and this will not be an issue afterward.
