### ISSUE TITLE
Seems to be incompatability with other mods that add mobs.

### ISSUE THREAD

**Issue by Exvious** [Cryptic-Mushroom/The-Midnight#378]
Currently, I have this mod and the mutant beasts mod added into my server. The nightmare dimension is awesome, but we are unable to explore it because for some reason, ONLY the mutant beasts will spawn there and they will spawn in unbelievable amounts. You cannot last 30 seconds in the new dimension because of the massive amount of mobs spawning in. I've altered the spawn rates for the mutant creatures mod, but still only the mutants will spawn there in large numbers. I was personally unable to find a config option related to overworld mobs spawning in the new dimension.

**Comment by Jonathing** [comment]
This issue was discussed previously on the discord server, if I recall correctly. We think this is an issue on Mutant Beasts' end, but if we find out otherwise, we'll update the issue.
