### ISSUE TITLE
Stuck prone after teleporting from rifter while being abducted (1.12.2)

### ISSUE THREAD

**Issue by jarquafelmu** [Cryptic-Mushroom/The-Midnight#380]
I accidentally teleported away from a rifter while I was being carried away prone. When I arrived at my teleport spot I was still prone. How do I stand back up?

**Comment by Jonathing** [comment]
We will no longer be updating the 1.12.2 version of The Midnight. https://www.minecraftforge.net/forum/topic/79304-112114-and-lts-system/
