### ISSUE TITLE
Tenebrum doors and trapdoors don't have transparency

### ISSUE THREAD

**Issue by TheMinecraftOverlordYT** [Cryptic-Mushroom/The-Midnight#381]
Tenebrum doors and trapdoors aren't see through, where there should be blank space there is just grey.
![2020-04-17_20 56 44](https://user-images.githubusercontent.com/14249937/79670683-dd865c80-8192-11ea-9a03-34d4883b0428.png)
![2020-04-17_20 56 58](https://user-images.githubusercontent.com/14249937/79670685-de1ef300-8192-11ea-8c00-1f8d9ca819d4.png)

**Comment by RedGalaxySW** [comment]
Fixed!
