### ISSUE TITLE
Console spam during the night

### ISSUE THREAD

**Issue by cestofmir** [Cryptic-Mushroom/The-Midnight#382]
On my modded server, I appear to get spam in the console when it is night-time. This same message constantly repeats itself. https://pastebin.com/FgcguUrA

This does not occur when it is daytime in the overworld. 

Any idea on what is going on? How can I fix this?

Here's a full server log (it was too big for pastebin): https://drive.google.com/file/d/1K1sZ8SyE-CNBuDobdZ71sKDtlUoQvK3G/view?usp=sharing

And debug: https://drive.google.com/file/d/1-e85_XbTgjoHCAYAAbGvM1i_foXkAMtv/view?usp=sharing

**Comment by RedGalaxySW** [comment]
We no longer support 1.12.2 versions of the Midnight. See README.md
