### ISSUE TITLE
Midnight Slabs should not throw exception for getVarientProperty()

### ISSUE THREAD

**Issue by BlackQuests** [Cryptic-Mushroom/The-Midnight#383]
As I've explained in [this issue](https://github.com/CJMinecraft01/DoubleSlabs/issues/38#issue-602551466) I am trying to make a modpack with various mods that include The Midnight and Double Slabs. So far every mod works (somewhat) perfectly with Double Slabs. Midnight is the only mod that actually crashes the game together with it. It is due to the fact that the [getVariantProperty()](https://github.com/Cryptic-Mushroom/The-Midnight/blob/30c5bf34dc8b0532e75fc48afc2b8e74d8874718/src/main/java/com/mushroom/midnight/common/block/BlockMidnightSlab.java#L52) method is overridden and throws a `UnsupportedOperationException()`. I think it would be smarter to instead not override the method to increase compatibility with other mods. I am however not as familiar with modding as you might be, so I respectfully understand if I'm wrong and you think it is not wise to change the method.

For extra details: The Double Slabs mod uses the method in [DoubleSlabsConfig.java#L37](https://github.com/CJMinecraft01/DoubleSlabs/blob/dd60dbad5821049b6d720f18773a5b74fa0ec4d6/src/main/java/cjminecraft/doubleslabs/DoubleSlabsConfig.java#L37) which is used to load the blacklist values including possible variant types that slabs might have.

If anything is unclear I would love to help.

**Comment by RedGalaxySW** [comment]
This issue is a 1.12.2 issue... We no longer support those versions of the Midnight... See README.md...
