### ISSUE TITLE
Passive-ish mods throughout the midnight

### ISSUE THREAD

**Issue by mtlemsani** [Cryptic-Mushroom/The-Midnight#386]
DO NOT REPORT ANY ISSUES ON THE 1.12.2 VERSIONS OF THE MIDNIGHT: THOSE VERSIONS ARE NO LONGER SUPPORTED AND ANY RELATING ISSUE WILL BE CLOSED AND IGNORED!!!

Explain the bug:
- What isn't working?
**The hostile mobs within the Midnight do not attack at all, or only if stood completely still (Except for the Nova). The Rifters will still pursue as if to attack then stop. It is actually quite creepy**
- How to reproduce the problem?
**Stand still and allow the rifter to walk as close as possible, after about 5 seconds it will hit you once. Stingers seem to be slightly more aggressive, but this issue still occurs. We never let them live too long after the first hit.**
- Does the game crash? How?
**The game does not crash**

If you have some screenshots, please include them. They are very helpful to understand the issue.
**Nothing really to screenshot. It would just be a Rifter standing staring at us. **

If you have found some remarkable log messages, please include only those messages (code block!!) and paste the complete log file in a gist/pastebin.

#### Environment
- Midnight: [midnight version]
**0.5.6**
- Forge: [forge version]
**1.15.2 31.1.46** 
- Did you use other remarkable modpacks, mods, resource packs or data packs, please list them here too.
**We are using a small modpack with 24 mods (listed below)**

AppleSkin | squeek502 | AppleSkin-mc1.15.2-forge-1.0.13.jar
Biomes O' Plenty | Forstride | BiomesOPlenty-1.15.2-10.0.0.345-universal.jar
Botania | Vazkii | Botania r1.15-382.jar
Cucumber Library | BlakeBr0 | Cucumber-1.15.2-3.0.5.jar
Curios API | TheIllusiveC4 | curios-FORGE-1.15.2-2.0.2.1.jar
FastFurnace | Shadows_of_Fire | FastFurnace-1.15.1-3.0.0.jar
FastWorkbench | Shadows_of_Fire | FastWorkbench-1.15.1-3.0.0.jar
Hwyla | TehNut | Hwyla-forge-1.10.8-B72_1.15.2.jar
Iron Chests | ProgWML6 | ironchest-1.15.2-10.0.3.jar
Just Enough Items (JEI) | mezz | jei-1.15.2-6.0.0.3.jar
Mekanism | bradyaidanc | Mekanism-1.15.2-9.9.20.412.jar
Mekanism Generators | bradyaidanc | MekanismGenerators-1.15.2-9.9.20.412.jar
Mekanism Tools | bradyaidanc | MekanismTools-1.15.2-9.9.20.412.jar
MixinBootstrap | LX_Gaming | MixinBootstrap-1.0.2.jar
Morpheus | Quetzi | Morpheus-1.15.2-4.2.50.jar
MrCrayfish's Furniture Mod | MrCrayfish | furniture-7.0.0-pre16-1.15.1.jar
Mystical Agriculture | BlakeBr0 | MysticalAgriculture-1.15.2-3.0.2.jar
Nature's Compass | Chaosyr | NaturesCompass-1.15.2-1.8.5.jar
Patchouli | Vazkii | Patchouli-1.15.2-1.2-31.jar
Performant | someaddon | performant-1.15-2.07m.jar
Placebo | Shadows_of_Fire | Placebo-1.15.2-3.0.2.jar
The Midnight | cipher_zero_x | themidnight-0.5.6.jar
Xaero's Minimap | xaero96 | Xaeros_Minimap_20.7.1_Forge_1.15.2.jar

**Comment by Jonathing** [comment]
Possible forge issue. On hold for now.

**Comment by FyreByrns** [comment]
I also have this issue with forge 31.1.46 and no other mods.

**Comment by Jonathing** [comment]
We updated The Midnight to Forge 31.2.0, so this should not be a problem. If it is, feel free to reopen this issue.
