### ISSUE TITLE
[feature] Add blocks, items and fluids to their proper vanilla tags

### ISSUE THREAD

**Issue by BedrockLegends** [Cryptic-Mushroom/The-Midnight#388]
Would you be kind to add your crafting tables to the tag:forge:workbench to help out modpack developers

**Comment by Jonathing** [comment]
Okay, we will work on adding Forge tags at a later date. Please do not open multiple issues on this topic.

**Comment by RedGalaxySW** [comment]
We'll take this into account once we're gonna rewrite the mod in 1.16
