### ISSUE TITLE
Ctrl + \ crashes client

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Cryptic-Mushroom/The-Midnight#389]
In our modpack that is in development, when any test player presses the ctrl + \ binding for key.midnight.config the client crashes. This happens across OS's (Windows & Linux) and Java versions (OpenJDK & Oracle).

#### Environment
- Midnight: 0.5.7-2
- Forge: 1.15.2 31.1.46
- [Survival in Chaos-0.25.1.zip](https://github.com/Cryptic-Mushroom/The-Midnight/files/4536152/Survival.in.Chaos-0.25.1.zip) I'm sending you this, because the pack is not published yet.
- https://pastebin.com/qWiGFjg5

Thank you,
CM

**Comment by ClaudiusMinimus** [comment]
Here is a bit more information:

When a player removed the binding for key.midnight.config his console started receiving a lot of spam errors as in the screenshot. The log was too big for Pastebin, so I asked him for a clip showing where the spam stopped https://pastebin.com/uaHzbATv
I hope this info helps!
![holger_spam_error](https://user-images.githubusercontent.com/17887664/80496888-0347fa00-8927-11ea-8644-9fef09948190.png)

**Comment by RedGalaxySW** [comment]
Fixed, should be released soon...
