### ISSUE TITLE
[1.15.2] Client crashes on hitting keybind in namefield of creating new world

### ISSUE THREAD

**Issue by dreckz** [Cryptic-Mushroom/The-Midnight#391]
DO NOT REPORT ANY ISSUES ON THE 1.12.2 VERSIONS OF THE MIDNIGHT: THOSE VERSIONS ARE NO LONGER SUPPORTED AND ANY RELATING ISSUE WILL BE CLOSED AND IGNORED!!!

Explain the bug:
- What isn't working?
Creating a new world crashes the client
- How to reproduce the problem?
As I was typing the word "testing" in the name field of the world name, 
- Does the game crash? How?
Yes, and it is a client crash.
Be clear and concise.

#### Environment
- Midnight: [0.5.7-2]
- Forge: [28.1.47]
- I used controlling for keybinds, and I may have switched the keybinds around
Crash REport:
https://paste.gg/p/anonymous/45a89c3655174e97ac3011d896d22cd4

EDIT:
Keybind set to "n" and crashes when pressing it

**Comment by Jonathing** [comment]
should be fixed in 0.5.7-3
