### ISSUE TITLE
Server Crash when entering chunk containing midnight rift

### ISSUE THREAD

**Issue by kgibson9489** [Cryptic-Mushroom/The-Midnight#392]
Explain the bug:
- What isn't working? Loading an overworld chunk containing midnight resources
- How to reproduce the problem? Enter an overworld chunk containing midnight
- Does the game crash? How? Server freezes and crashes with high tick rate

Be clear and concise.

If you have some screenshots, please include them. They are very helpful to understand the issue.

If the game crashes, please paste the crash report here (code block!!) or in a gist/pastebin. When the game crashes, the launcher will probably show you a link to open the crash report (old launchers just shows the crash report itself).
Crash Log: https://pastebin.com/TGxv3L7Q

If you have found some remarkable log messages, please include only those messages (code block!!) and paste the complete log file in a gist/pastebin.
https://pastebin.com/UpTrFEsF

#### Environment
- Midnight: 0.5.6
- Forge: 31.1.46
- Did you use other remarkable modpacks, mods, resource packs or data packs, please list them here too. Initially we noticed that these crashes happened when loading a specific Dungeon Crawl chunk, but that area also contains midnight. Here's a link to the related issue: https://github.com/XYROC/DungeonCrawl/issues/30

**Comment by Jonathing** [comment]
This appears to be a mod compatibility issue. A similar issue is present in Modding Legacy's Lava Monsters which I have also looked at and am unable to find any narrow cause or fix for it, where the server hangs when the server tries to load a chunk for a structure or entity.

**Comment by kornfan6589** [comment]
#403 

This could actually be the issue we are having... Tagging because the "crash" being described is the same, which marks it hard to pin down the cause.

**Comment by kornfan6589** [comment]
#403 Did indeed fix this issue.
