### ISSUE TITLE
Using 90% of shaders causes lighting issues in the overworld and midnight demension

### ISSUE THREAD

**Issue by DeadShadow44** [Cryptic-Mushroom/The-Midnight#395]
Mobs in the overworld near a rift portal appear white or a distorted orange whilst using most shaders. Once in the midnight demension the world will appear a bright white, or a pitch black.

Photo of the midnight realm:
![2020-05-02_00 14 06](https://user-images.githubusercontent.com/64676887/80855851-c8ccbd00-8c98-11ea-828d-ec8bee21310f.png)

Glowing mobs from the overworld:
![2020-05-02_17 19 32](https://user-images.githubusercontent.com/64676887/80855886-25c87300-8c99-11ea-99f4-133f05480c14.png)

Midnight version: 0.4.7
Forge version: forge-28.2.0
Minecraft 1.14.4

Thanks

**Comment by Jonathing** [comment]
Duplicate of #337
