### ISSUE TITLE
Midnight lava giving water instead

### ISSUE THREAD

**Issue by SillyOWilly** [Cryptic-Mushroom/The-Midnight#397]
Explain the bug:
- What isn't working?
Midnight Lava is currently unobtainable
- How to reproduce the problem?
While using a rockshroom bucket, pick up the lava that can be found underground in the midnight, Instead of getting a rockshroom bucket full of lava the player recieves a "Dark Water Rockshroom Bucket" 

Note: I have not tested if this issue is the same with regular buckets or just for rockshroom ones
- Does the game crash? How?
Game does not crash

#### Environment
- Midnight: [0.5.7-3]
- Forge: [1.15.2]
- Did you use other remarkable modpacks, mods, resource packs or data packs, please list them here too.

**Comment by RedGalaxySW** [comment]
This is intentional behaviour for now. You can obtain miasma by using a normal bucket.
