### ISSUE TITLE
[discussion] Small Improvements thread

### ISSUE THREAD

**Issue by SillyOWilly** [Cryptic-Mushroom/The-Midnight#399]
I am making this thread for people in the comments as well as myself to suggest small improvements to the mod

The things I can think of off the top of my head are:

Only about 1-2 archaic shards can be found per trench stone cluster, considering the fact that its just glass it should either drop more shards per block or contain more blocks per cluster to make archaic glass a viable replacement for over world glass

I also suggest archaic glass becomes dye-able, keeping its interesting pattern but changing colors based on the dye provided

I suggest the bombs get a mini-rework as currently they are only viable weapons to use against other players as many of their effects don't work or don't really matter when fighting hostile mobs

I think portals to the midnight should either be more common or the player should have a way of obtaining dark pearls in the over world in order to access the midnight, dark pearls should also be consumed on creation of a portal instead of staying/having no animation

Trees in the midnight should have obtainable saplings so the player may farm midnight woods closer to their base or in the overworld

Stinger hitboxes should be enlarged slightly as they are very difficult to hit even you're literally on top of them

When a deceitful snapper bites back it should have its own debuff instead of just using slowness IV

Creepers that explode while under the "pollinated" effect create black particles even though pollinated particles are usually a yellow-green

There are many more small changes that can be made to improve the mod, please leave your own in the comments!

**Comment by Jonathing** [comment]
We'll take these suggestions into consideration when writing the rewrite.
