### ISSUE TITLE
Nightstone Furnaces dont stop burning with invalid top items

### ISSUE THREAD

**Issue by SillyOWilly** [Cryptic-Mushroom/The-Midnight#400]
Explain the bug:
- What isn't working?
When an item is incompatible with the top of a regular furnace but it's already burning it'll still lose fuel, this is not true with a nightstone furnace
- How to reproduce the problem?
Place a nightstone furnace, load fuel (dark pearls), begin cooking an item that is valid (ore, stag flanks), take the item out and place one that is invalid, the furnace will not stop burning as long as the invalid item is present in the top-slot
- Does the game crash? How?
Game does not crash

#### Environment
- Midnight: [0.5.7-3]
- Forge: [1.15.2]
- Did you use other remarkable modpacks, mods, resource packs or data packs, please list them here too.
No remarkable mod packs

**Comment by RedGalaxySW** [comment]
We'll take this into consideration in the 1.16 rewrite...

**Comment by Jonathing** [comment]
This might be due to the update to Forge 31.2.0, but when testing for this issue, I am not able to reproduce it. The furnace loses fuel as intended.
![https://i.imgur.com/vTfttIA.png](https://i.imgur.com/vTfttIA.png)
This is also true if there are dark pearls in the bottom slot.
