### ISSUE TITLE
[bug] Deadwood Fences Not Connecting

### ISSUE THREAD

**Issue by SillyOWilly** [Cryptic-Mushroom/The-Midnight#401]
Explain the bug:
- What isn't working?
Dead wood fences do not display the proper texture when connected, while the hitbox of the fence changes the actual look of the fence itself stays as if it were a single fence pole by itself
- How to reproduce the problem?
Make a deadwood fence, place 2 next to each other (not diagonally), fences will not connect
- Does the game crash? How?
Game Does Not Crash

#### Environment
- Midnight: [0.5.7-3]
- Forge: [1.15.2]
- Did you use other remarkable modpacks, mods, resource packs or data packs, please list them here too.
No remarkable mods

![2020-05-07_01 26 22](https://user-images.githubusercontent.com/64880969/81257802-2ac35480-9002-11ea-83ac-058569d5403e.png)
![2020-05-07_01 24 23](https://user-images.githubusercontent.com/64880969/81257806-2e56db80-9002-11ea-9c18-ea4401706633.png)

**Comment by Jonathing** [comment]
Fixed.

![2020-10-17_21 26 00](https://user-images.githubusercontent.com/18154752/96356642-8c164600-10bf-11eb-857b-142ecde3f4bc.png)
