### ISSUE TITLE
[1.15.2] Spawning Midnight mobs outside The Midnight Dimension by biome's spawn list will cause world to hang forever

### ISSUE THREAD

**Issue by TelepathicGrunt** [Cryptic-Mushroom/The-Midnight#403]
_(Scroll to bottom for the fix I found for this bug)_ 
I have brought up this issue before on The Midnight discord here but I was told to find the source of the bug myself:
https://discord.com/channels/382958565125521412/492341085553819658/692477886552080504

So what I have found is that this is not a mod compatibility issue as I can easily reproduce this bug with just The Midnight and Vanilla alone. What I have done was I added these lines of code to the end of setup(FMLCommonSetupEvent event) method.
```
 Biome biome = ForgeRegistries.BIOMES.getValue(new ResourceLocation("minecraft:desert"));
Method method = ObfuscationReflectionHelper.findMethod(Biome.class, "addSpawn", EntityClassification.class, Biome.SpawnListEntry.class);
try {
     method.invoke(biome, EntityClassification.CREATURE, new Biome.SpawnListEntry(MidnightEntities.NIGHTSTAG, 100, 1, 3));
} catch (Exception e) { e.printStackTrace(); }
```

What this does is it adds the Night Stag mob to vanilla desert biomes. When I do this, create a new world, /locate desert_pyramid, and teleport to the desert found, the would hang forever and nothing loads anymore. Outside of an IDE, this hang would require Task Manager to kill and hurts The Midnight's compatibility with any mod that import's The Midnight's Night Stag mob to their biome out side the dimension. It also affects any mod that tries to spawn The Midnight's biomes outside of the dimension as well.

Upon the hang, I paused all the threads and these two threads seems to be is where the hanging is occurring:
![image](https://user-images.githubusercontent.com/40846040/81463903-368e5280-918b-11ea-8aea-4c96916fb621.png)
![image](https://user-images.githubusercontent.com/40846040/81463906-40b05100-918b-11ea-9e3c-2761a8183e13.png)

It seems to point to this method as being the cause of the hang and any midnight mob that uses this method for spawning will also cause the hang.
https://github.com/Cryptic-Mushroom/The-Midnight/blob/d1bfdba71b6ff23b9dc2054093c092e32c1925e3/src/main/java/com/mushroom/midnight/common/registry/MidnightEntities.java#L197-L200

Upon closer inspection, I noticed that `world.getWorld().getBlockState(blockpos).canEntitySpawn(world, blockpos, entityType);` is odd as other placementPredicates doesn't call getWorld() at all. When I changed that line to just `world.getBlockState(blockpos).canEntitySpawn(world, blockpos, entityType);`, the mobs now spawn just fine and no hanging happens anymore!

Yep. This super weird bug that was hurting mod compatibility was caused by an extra getWorld() call lol. I'm not sure exactly why this causes the bug but my guess is that the current world, which is WorldGenRegion, is what holds the current chunk being made and can access it as it make it. But by calling getWorld() on it, we get World instead and when we call .getBlockstate on that, it then tries to get the chunk that is in the process of being created and forces the code to wait... while also being in the code that's generating the chunk itself and causing it to wait forever. 

I hope this helps! The fix should be super easy.

**Comment by RedGalaxySW** [comment]
Wow, this is helpful as I have been gazing upon this issue for quite a while already. Thank you so much! I'll take a look once I have time...
Why this works in the Midnight itself is also no wonder: the Midnight doesn't yet use world-gen mob spawning so `world` is never a `WorldGenRegion`...

**Comment by kornfan6589** [comment]
Confirmed Fix for the issue we were having!
