### ISSUE TITLE
Possible issue with Stinger Egg

### ISSUE THREAD

**Issue by Zakkajj** [Cryptic-Mushroom/The-Midnight#411]
DO NOT REPORT ANY ISSUES ON THE 1.12.2 VERSIONS OF THE MIDNIGHT: THOSE VERSIONS ARE NO LONGER SUPPORTED AND ANY RELATING ISSUE WILL BE CLOSED AND IGNORED!!!

Explain the bug:
- What isn't working?
Possible issue with Stinger Eggs spamming console
- How to reproduce the problem?
Not sure, a player is in the midnight when console spam occurs.
- Does the game crash? How?
No crash from issue yet.
Be clear and concise.

If you have some screenshots, please include them. They are very helpful to understand the issue.

![stinger egg issue](https://user-images.githubusercontent.com/66444192/83810958-f5546a00-a686-11ea-90cd-5792f4109f6b.jpg)

If the game crashes, please paste the crash report here (code block!!) or in a gist/pastebin. When the game crashes, the launcher will probably show you a link to open the crash report (old launchers just shows the crash report itself).

If you have found some remarkable log messages, please include only those messages (code block!!) and paste the complete log file in a gist/pastebin.

#### Environment
- Midnight: [midnight version] **0.5.7-3**
- Forge: [forge version] **1.15.2-31.1.46**
- Did you use other remarkable modpacks, mods, resource packs or data packs, please list them here too.

Quark 2.1-240
Quark Oddities 1.15.2
Nether Spread 1.15-3.0
Xerca Music 2.1
Biomes O Plenty .345
AutoRegLib 40

**Comment by Jonathing** [comment]
Ahhhh! I keep forgetting to remove my debug code! Thanks for pointing that out.

**Comment by Jonathing** [comment]
Oh whoops, I just saw your version. I removed this debug code in 0.5.8.
