### ISSUE TITLE
version 1.15.2 mod cant be loaded by Forge

### ISSUE THREAD

**Issue by FunWithFlaggs** [Cryptic-Mushroom/The-Midnight#412]
Minecraft version 1.15.2 Forge version 1.15.2-forge-31.2.0

'The Midnight (midnight) encountered an error during the common_setup event phase'

That error pops up when starting Minecraft, cant get to main menu.
See error logs attached

[error.log](https://github.com/Cryptic-Mushroom/The-Midnight/files/4733216/error.log)

**Comment by Jonathing** [comment]
java version?

**Comment by FunWithFlaggs** [comment]
`[10:08:45 INFO]: System.getProperty('os.arch') == 'x86_64'`
`[10:08:45 INFO]: System.getProperty('java.version') == '12'`

**Comment by Jonathing** [comment]
That's why. We currently only support Java 8 and have no plans to support Java 9 or higher.

**Comment by sandtechnology** [comment]
Just a workaround for user searching: add jvm args:`--add-opens java.base/jdk.internal.reflect=ALL-UNNAMED`

Reference: https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m
