### ISSUE TITLE
Shaders make Midnight sky white

### ISSUE THREAD

**Issue by 0timnus0** [Cryptic-Mushroom/The-Midnight#415]
The sky will always be white no matter which shader I use.

- Midnight version: 0.5.9 (1.15.2)
- Forge: 1.15.2 31.2.0
- I'm using the preview version of optifine for 1.15.2

**Comment by RedGalaxySW** [comment]
We do not support shaderpacks right now and we'll neither in the upcoming versions. Sorry.

**Comment by Jonathing** [comment]
FYI, OptiFine is only tested to support Forge 31.1.63 while The Midnight supports 31.2.0.
