### ISSUE TITLE
[bug] Shadowroot chest texture is messed up.

### ISSUE THREAD

**Issue by obeeblue** [Cryptic-Mushroom/The-Midnight#417]
![shadow](https://user-images.githubusercontent.com/48190572/84889403-a8d93900-b04d-11ea-905c-d5f1e4190f38.png)

**Comment by RedGalaxySW** [comment]
It's only an image but the bug obvious and straightforward. But _what version of the Midnight is this_?

**Comment by obeeblue** [comment]
> It's only an image but the bug obvious and straightforward. But _what version of the Midnight is this_?

**Comment by obeeblue** [comment]
> It's only an image but the bug obvious and straightforward. But _what version of the Midnight is this_?

**Comment by RedGalaxySW** [comment]
Ok thanks. Please follow the issue template next time: it helps us getting the information we need. I'll mark this to be considered in the 1.16 rewrite as it's not a game-breaking bug.

**Comment by obeeblue** [comment]
> Ok thanks. Please follow the issue template next time: it helps us getting the information we need. I'll mark this to be considered in the 1.16 rewrite as it's not a game-breaking bug.

My bad! I saw it in the modpack Valhelsia 2 and thought I'd try to help out :)

**Comment by Jonathing** [comment]
@obeeblue sounds good mate. We're shifting our focus for 1.16 when Forge is ready for that, which is why we aren't too worried about it for now, but thanks for the report!

**Comment by Jonathing** [comment]
Unfortunately, this bug *will not* be fixed in 0.5.10. Instead, we will make sure that the chests are correctly mapped in 0.6.0 and onward.

**Comment by ShadewRG** [comment]
Fixed!
