### ISSUE TITLE
Little Warning

### ISSUE THREAD

**Issue by NihilEntropy** [Cryptic-Mushroom/The-Midnight#420]
Might want to give some indication that throwing a dark pearl spawns a portal...
![2020-06-20_21 01 23](https://user-images.githubusercontent.com/52515211/85217008-f2c16800-b348-11ea-9e6e-1fe97a1e4a70.png)

**Comment by RedGalaxySW** [comment]
This works as intended. We'll be revamping the rifts in 1.16 and we will or will not remove this feature
