### ISSUE TITLE
loading midnight java file

### ISSUE THREAD

**Issue by pday890** [Cryptic-Mushroom/The-Midnight#422]
hi im kind of new to modding so i look at some tutorials and loved your mod so i decided to download it. ive got the files inside of the mod folder inside of another folder i named midnight. i load up forge go into mods and its not there so i click "open mods folder"and then click on the java file but i get this error
![image](https://user-images.githubusercontent.com/67290192/85328107-08a96700-b4c8-11ea-9a27-cc7f674baf39.png)

if you can see the image it reads
line 1
char 1
org is undefined

am i doing something wrong?

**Comment by Jonathing** [comment]
What are you trying to do? All you need to do is put the midnight jar file in the mods folder and make sure you're running 1.15.2 with Forge 31.2.0. I don't try and launch the jar file itself.

**Comment by pday890** [comment]
i am just trying to run the mod but its not appearing in the mods section of forge launcher

**Comment by Jonathing** [comment]
Do you mind sending screenshots? I don't know how to help you other than to say that you just need to make sure the .jar file is in the correct place.

**Comment by pday890** [comment]
![image](https://user-images.githubusercontent.com/67290192/85328933-83bf4d00-b4c9-11ea-8df4-71a636f9272f.png)

![image](https://user-images.githubusercontent.com/67290192/85328973-92a5ff80-b4c9-11ea-9db8-aa14160b0920.png)

![image](https://user-images.githubusercontent.com/67290192/85329036-a94c5680-b4c9-11ea-8b1f-a08d00627a69.png)

![image](https://user-images.githubusercontent.com/67290192/85329079-bcf7bd00-b4c9-11ea-85e6-81e97c7de368.png)

so im trying to load the mod to make sure it can find it

**Comment by Jonathing** [comment]
You are not supposed to unarchive the .jar file. All you need to do is put the .jar file in the mods folder and it will load for you. Make sure you restart your game when you do that.

**Comment by pday890** [comment]
thanks a bunch this has fixed it
is it the same for all mods?

**Comment by RedGalaxySW** [comment]
Yes.

If you wanna modify the mod's sources, download the sources then or clone it using git, and then open the sources folder with Eclipse or IntellIJ... Extracting the jar file is hopeless as it only contains binary files which you cannot modify and Forge can't determine what they're supposed to do...

**Comment by RedGalaxySW** [comment]
Gonna close this now as it is not something we need to fix... If you have further questions ask them on discord...
