### ISSUE TITLE
Botania & Immersive Engineering Incompatibility

### ISSUE THREAD

**Issue by bloche14** [Cryptic-Mushroom/The-Midnight#424]
When The Midnight is installed, the revolver from Immersive Engineering does not fire on right click, and the rod of the shaded mesa from botania does not function correctly (acts as if you used the left-click function when you use the right click function)

- Midnight: 0.5.9
- Forge: 31.2.9
- Tested with Botania r1.15-386 and Immersive engineering 0.15-103 (and their libraries) only

**Comment by Jonathing** [comment]
Right now, mod compatibility is the last of our worries, especially since we're going to be rewriting The Midnight for 1.16.1. I might consider revisiting this when we have the mod underway, but I will be closing this for now.
