### ISSUE TITLE
[1.15.2] Crash upon entering dimension

### ISSUE THREAD

**Issue by Mysteriaa** [Cryptic-Mushroom/The-Midnight#426]
# The Bug

See title. Sorry if this is messy, I joined Github just to find help here. ;;

When I entered the Midnight, my game had crashed after I was greeted with a loading screen. I had also crashed when I reopened my game to load up the save file again.

## Steps to Reproduce:
1. Jump into portal. Brief loading screen. Crash.
2. Reopen game.
3. Load up save file where crash occurred. Crash again and continue to do so every time it is opened.

## Environment
- Minecraft: [1.15.2]
- Midnight: [0.5.9]
- Forge: [31.2.20]
- I have a few significant mods, those being Endergenic Expansion, Cazmaniya, Liroth, BiomesYou'llGo, Biomes O'Plenty and Mubble, if that matters, though I do suspect at least one of my mods is responsible for the issue. ;;

Crash log from entering dimension: https://pastebin.com/6PjZa27C
Crash log after reloading save: https://pastebin.com/cwkk8UXW

**Comment by Coreboom** [comment]
I had the same issue, someone said it was something to do with optifine.

**Comment by RedGalaxySW** [comment]
This issue has nothing to do with the Midnight. Has something to do with either Optifine or Forge - please report it there...
