### ISSUE TITLE
1.12.2 Crash Client side

### ISSUE THREAD

**Issue by doarlock** [Cryptic-Mushroom/The-Midnight#429]
Here is the crash report: 
[crash-2020-07-05_20.07.01-client.txt](https://github.com/Cryptic-Mushroom/The-Midnight/files/4876291/crash-2020-07-05_20.07.01-client.txt)

**Comment by Jonathing** [comment]
we don't support 1.12.2 or 1.14.4

**Comment by Jonathing** [comment]
the crash was caused by the dimension ID being taken. Make sure id -23 is free.
