### ISSUE TITLE
1.15.2 Your Discord Invite Link is Expired, Please Update It

### ISSUE THREAD

**Issue by Shunkawarakin** [Cryptic-Mushroom/The-Midnight#434]
# The Bug

Attempt to join Midnight Discord using link from GitHub, Discord informs that the invite has expired.

# Steps to reproduce

Click large candy-colored 'Discord' button at bottom of Github page.

# Important Notes

Not an emergency but problematic community-wise. Thank you for updating this when you have the cycles to do so.

**Comment by Jonathing** [comment]
Discord invite link updated on both the GitHub README.md on the front page of the project and the CurseForge page.
