### ISSUE TITLE
Request: Fabric port

### ISSUE THREAD

**Issue by vico93** [Cryptic-Mushroom/The-Midnight#441]
Is there any plans for it?

Thanks in advance!

**Comment by Jonathing** [comment]
No plans to port to Fabric.

**Comment by vico93** [comment]
I cant find the license of the repo (i assume its GPL according to CurseForge), but can other modder fork this repo to add support to Fabric?

**Comment by ShadewRG** [comment]
You should look at the wiki for the new license, which will apply to all builds of the rewrite. For all older versions GPL v3 applies.

Speaking of forking, you may fork the repo to make pull requests. We won't accept pull requests with new features, just translation updates and bug fixes. Additionally, we will not be supporting any 0.5.x version or below after we release 0.5.10 (which happened just yet), hence making a pull request won't work.

When it comes to forking and porting to Fabric, you may do that with old builds we no longer support but the new license will apply to all the content in the rewrite, meaning that distributing a Fabric version globally is effectively not allowed (sharing it locally with friends is always ok dw).

If you ever make a port to Fabric we'd love to know that though :)

**Comment by ShadewEnder** [comment]
We eventually decided to go for an official Fabric port with the rewrite since porting over to Fabric seemed affordable for us. Just letting you know about that.

**Comment by vico93** [comment]
Oh, great news, although i abandoned Fabric 1.16 entirely to stick with Forge 1.12 (due to some critical mods of my modpack doesn't being updated past it, like [Pillar](https://github.com/Vazkii/Pillar) or Forge/Spigot hybrids to run [TrainCarts](https://www.spigotmc.org/resources/traincarts.39592/)).

BTW good work with the port!

**Comment by Jonathing** [comment]
Closing. Since Shadew left the team, there will not be a Fabric version of The Midnight. It simply isn't feasable.
