### ISSUE TITLE
[1.12.2] Bug Report 2d textures

### ISSUE THREAD

**Issue by Frannycisc0** [Cryptic-Mushroom/The-Midnight#455]
I just started up my new server and for some reason, textures like the blue unstable fruits and tall lumen bud aren't loading properly so I was just wondering if there was a way to fix it

**Comment by Jonathing** [comment]
If you have better foliage installed, uninstall or disable it.

**Comment by Frannycisc0** [comment]
[https://docs.google.com/document/d/1nQkV7Zmpl43uoM7lcznIjzkRRDLl9mmeVIkOUSPNQYc/edit?usp=sharing](url)

**Comment by Jonathing** [comment]
Like I said. Remove or disable Better Foliage. We don't support 1.12.2 issues anymore.
