### ISSUE TITLE
[MC 1.15.2] Attempting to open config GUI in world create screen crashes the game

### ISSUE THREAD

**Issue by G-Guy** [Cryptic-Mushroom/The-Midnight#465]
~~Name says it all - When creating new world in Minecraft, pressing letter W when in name field it causes crash.~~ Attatching crash log and debug.log. Crash log has been modified by MoreCrashInfo mod if it's important.
[debug.log](https://github.com/Cryptic-Mushroom/The-Midnight/files/6091055/debug.log)
[crash-2021-03-05_15.12.57-client.txt](https://github.com/Cryptic-Mushroom/The-Midnight/files/6091056/crash-2021-03-05_15.12.57-client.txt)

Edit by Jonathing: issue has been narrowed down to the keybind for the config screen being set to w and being used in the world create screen. Will probably find a way to disable the config screen in world create

**Comment by Jonathing** [comment]
Closing. As of right now, we probably won't have a custom config GUI like we did in 0.5.x.
