### ISSUE TITLE
[MC 1.16.4 (April Fools 2021)]  The Midnight (midnight) encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by TheDarkRisen** [Cryptic-Mushroom/The-Midnight#466]
When I'm launching Minecraft these message appear => The Midnight (midnight) encountered an error during the common_setup event phase

## Environment

- Minecraft: 1.16.4
- Midnight: 1.0-final
- Forge: 35.1.36
[crash-2021-04-01_19.39.47-fml.txt](https://github.com/Cryptic-Mushroom/The-Midnight/files/6244763/crash-2021-04-01_19.39.47-fml.txt)

**Comment by Jonathing** [comment]
Wow, I can't believe our april fool's joke crashed because of an issue with my dependency. Well, thanks for reporting the crash nonetheless. I'll remove the verification utility from the april fool's joke since it really isn't needed. Do you mind also sending the latest.log as well, please?

**Comment by FoxShadew** [comment]
This probably indicates we have to do more test releases

**Comment by TheDarkRisen** [comment]
Sorry, I had problems with internet yesterday.
When it will be possible to play on 1.16.4? ;d

[latest.log](https://github.com/Cryptic-Mushroom/The-Midnight/files/6248136/latest.log)

**Comment by FoxShadew** [comment]
We don't have a planned release date yet. However the April fools release is a direct snapshot of the rewrite so you can see an approximate amount of progress we're making

**Comment by Jonathing** [comment]
Forgot to close this. We figured out what the issue was not too long ago. Come join our Discord server, I'll be releasing the first test build very soon!
