### ISSUE TITLE
[1.16.5] Mod loading error has occurred - server crash on bootup

### ISSUE THREAD

**Issue by Yourname942** [Cryptic-Mushroom/The-Midnight#469]
# The Bug

The mod is consistently crashing the server upon bootup. 

# Steps to reproduce
boot up the server
somewhere during bootup  the crash occurs

# Important Notes

crash log:
https://gist.github.com/Yourname942/2110ca6bc0fff91a9bce235ad7dea594
latest log:
https://gist.github.com/Yourname942/534f758589f5c47954bd6f992390d7ed
debug log:
https://gist.github.com/Yourname942/6a01f21391e27af7237d9911f8f26b4a
## Environment

- Minecraft: [1.16.5]
- Midnight: [midnight-universal-1.0-final]
- Forge: [36.1.2]
- Did you use other remarkable modpacks, mods, resource packs or data packs, please list them here too. If your issue involves a problem with rendering or GUI, make sure to list all clientside mods as well.

**Comment by Jonathing** [comment]
This has been fixed in the test builds, but if you really care about the April fool's build that much, I'll update it in a second.

**Comment by Yourname942** [comment]
I didn't realize it was a joke build :)
