### ISSUE TITLE
Miasma does not have submerged overlay

### ISSUE THREAD

**Issue by ZombieEnderman5** [Cryptic-Mushroom/The-Midnight#48]
As the name suggests, the still miasma block isn't animated, but the flowing one is. So is miasma surface, which leads me to ask a question: Why isn't still miasma animated? Feel free to close this issue if it's a duplicate or has already been fixed in dev, but not released.

**Comment by ZombieEnderman5** [comment]
A further note: Miasma doesn't seem to have a shader for being inside it, unlike water and lava. Perhaps this should be added? Or maybe it does have a shader, I wouldn't know.
![2018-10-23_20 42 09](https://user-images.githubusercontent.com/37218872/47398948-6fc7b480-d704-11e8-970e-44539391c666.png)
![2018-10-23_20 42 20](https://user-images.githubusercontent.com/37218872/47398949-6fc7b480-d704-11e8-881f-83d69ce3f66e.png)

**Comment by Terenx** [comment]
last time I checked still miasma was animated like lava, its just like prismarine, the texture slowly changes

**Comment by Terenx** [comment]
It is animated, I just double checked, it animates like lava does
