### ISSUE TITLE
Shader issue

### ISSUE THREAD

**Issue by jaesunn** [Cryptic-Mushroom/The-Midnight#55]
When you have shaders on, the black part of the rift disappears and only shows the rock particles.

**Comment by Andromander** [comment]
Sounds like an Optifine issue, which cannot br fixed on our side due to Optifine being closed source and hacky in how it changes the shader mechanics.

**Comment by Terenx** [comment]
please don't use optifine with mods that add stuff unless it says its optifine compatible

**Comment by gegy1000** [comment]
This will be resolved in the next version.
