### ISSUE TITLE
Potential bounding box memory leak.

### ISSUE THREAD

**Issue by Darkhax** [Cryptic-Mushroom/The-Midnight#56]
When entering the midnight on the SpookyJam server, the ram usage increased drastically. Running VisualVM on the server revealed that a lot of stuff with bounding boxes is being done, and those bounding boxes are not being garbage collected. 

![image](https://user-images.githubusercontent.com/2250798/47610901-bfb4bd00-da1d-11e8-8d84-07b13ef069ad.png)

**Comment by Terenx** [comment]
Is this consistent with every time you go into the midnight, or only the first time, usually you get a large lag spike when generating a new dimension
