### ISSUE TITLE
Rifters Needs an Escape Rope

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/The-Midnight#60]
Sure, rifters can teleport behind players and get into their houses, but most houses are usually sealed with a door or heck full blocks if the homeowner is sporting a piston door, if the player is not looking the the direction of the rifter, they can teleport through, but when inside, they cant teleport out, even if the player is looking away from the rifter dragging them off, rifters should be able to do one of three things after grabbing their prey, either they instantly teleport 10-20 blocks closer to the rift, making it potention for someone to be instantly sent to the midnight if a rift spawns close enough; they could go back to where they were 1 or 2 teleports ago, causing fear of rifters because of how teleportation works a player wouldn't know if the rifter walked most the way then teleported a little bit or went from the rift straight to the player, and the last one is let them teleport like they would when a player has its back turned, this causes unpredictability and makes getting grabbed more of a risk because instead of being garunteed one escape at a certain distance it can be uncertain

**Comment by gegy1000** [comment]
Closed with https://github.com/Cryptic-Mushroom/The-Midnight/commit/78f3b969aefe627c0bf60381c7ae6d150201f35d, Rifters can only teleport where they would be able to reach by walking.
