### ISSUE TITLE
[bug] Tree bases are weird

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/The-Midnight#63]
Shadowroot saplings can be grown into trees on a single block although its base is 3x2, however, a dark will ow's base is 5x4, and REQUIRES that space to be grown into the full tree.        EDIT:Found out dark willow bases vary, the smallest I could get was 4x4, but it still requires sufficient space to grow.

**Comment by gegy1000** [comment]
We will likely soon port shadowroot saplings to use the same structure-block based generation as dark willows, which will introduce this consistency.

**Comment by Jonathing** [comment]
We are rewriting The Midnight and thus trees and other plant life in the dimension will be changed accordingly.
