### ISSUE TITLE
list of suavis issues

### ISSUE THREAD

**Issue by five0five** [Cryptic-Mushroom/The-Midnight#73]
-it places itself on a random part of the tile like flowers, which means it intercepts blocks
-particles are purple from what I can see, it makes sense if they're more blue
-it sounds like grass when placed, needs a more slimy sound
-it probably shouldn't spawn the particles if the player who broke it is in creative
-you can walk through it, its supposed to be a solid block
-it only ever drops one slice, it should drop about 3-5 or something

**Comment by arthurbambou** [comment]
1,3,5,6 are fixed

**Comment by arthurbambou** [comment]
particles are now blue

**Comment by arthurbambou** [comment]
all issue are fixed now let's fix generation
