### ISSUE TITLE
Suavis is spawning underground

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/The-Midnight#82]
when checking to see if the ores were spawning right, I found this little beauty at Y 25
![2018-11-23_18 30 59](https://user-images.githubusercontent.com/44249598/48963145-214f4500-ef52-11e8-8a12-9a5b13d53cff.png)

**Comment by arthurbambou** [comment]
It's weird normally they only generate over Midnight Grass

**Comment by Terenx** [comment]
Yeah but I found this one underground, seems to be very rare to find in in the first place, I spent the better half of an hour looking for another instance of it but I couldn’t

**Comment by arthurbambou** [comment]
I think it’s a vanilla bug because I have done a check up to prevent this

**Comment by five0five** [comment]
given the extreme rarity of this occurrence and lack of (negative) effect on gameplay when it does occur, I think its probably best to close this issue (for the time being)

**Comment by Terenx** [comment]
Probs a good idea
