### ISSUE TITLE
Bladeshroom duplication

### ISSUE THREAD

**Issue by five0five** [Cryptic-Mushroom/The-Midnight#99]
1. Harvest a Bladeshroom's cap

2. Break the stem

3. Place the stem on the ground (it will place a brand new bladeshroom, with a cap)

**Comment by gegy1000** [comment]
Hmm, how should we handle this? Should harvesting the bladeshroom without a cap give you a capless item?

**Comment by gegy1000** [comment]
That works nicely. It also removes the need for the bladeshroom plant item.
